### ISSUE TITLE
"Couldn't execute ghc --numeric-version" with latest VS Code

### ISSUE THREAD

**Issue by simonmichael** [haskell/vscode-haskell#1010]
I'm cc'ing this from a recent debug session in the HLS chat room, for anyone else who hits this problem before the bugfix release arrives. In some projects, when using the current VS Code release (1.84.2), vscode-haskell fails at startup with this error. This branch fixes it: https://github.com/fendor/vscode-haskell/tree/test/always-set-cwd

**Comment by fendor** [comment]
Closed by #1011 
Next release will be soon to roll out this change.
