### ISSUE TITLE
A setting for additional cabal command line arguments

### ISSUE THREAD

**Issue by unorsk** [haskell/vscode-haskell#1025]
**The problem**

I am working on my small application that has an external dependency, which doesn't support `base 4.19`, yet. It's a matter of time until the dependency gets updated and republished, but until then I'm using cabal option `--allow-newer` to build and test my project.
The problem is that the VS code extension stops working once I add the dependency.
I'm getting this error
```
Failed to find the GHC version of this Cabal project. Error when calling cabal exec -v0 -- ghc --print-libdir
```

**Suggested solutions**

I haven't found a way around this and thought that may be if the extension had a configuration option (like a setting) through which we could pass any additional arguments to cabal. So I could just use that.

It might probably be useful in some other situations too.

Another solution could be just introducing an option to manually specify the libdir so that the extension would need to call cabal.

Maybe I am just missing something and there already is a workaround for a situation like mine.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

If this is a cabal project, it might make sense to configure your project to allow-newer, e.g. `cabal configure --allow-newer` will create a `cabal.project.local` file with the contents:
```
allow-newer: all
ignore-project: False
```

then `cabal build` will work without `--allow-newer` and HLS will also work as expected.

There is no way to pass extra cabal cli arguments.

**Comment by unorsk** [comment]
@fendor, thanks a lot! That saved my day!

**Comment by fendor** [comment]
Happy to hear that! Closing this issue, feel free to open new issues if you encounter other problems.
