### ISSUE TITLE
TSLint is deprecated

### ISSUE THREAD

**Issue by bzm3r** [haskell/vscode-haskell#1042]
# Issue Description

The TSLint extension is deprecated: 

- [VS Code Marketplace: TSLint](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) page links to [the following](https://blog.palantir.com/tslint-in-2019-1a144c2317a9) in its deprecation notice
- The same notice recommends using [ESLint](https://github.com/typescript-eslint/typescript-eslint#typescript-eslint) instead

# Suggested Action

Remove TSLint from recommended workspace extensions, and instead use ESLint.

**Comment by fendor** [comment]
You fixed this, right? Closing as fixed :)
