### ISSUE TITLE
Could Handle hieExecutablePath separately for *nix and Windows

### ISSUE THREAD

**Issue by QuietJoon** [haskell/vscode-haskell#161]
I'm working on many Haskell projects shared by Google Drive.
However, to work across Linux(my home) and Windows(my company) on the same directory, I have to change `languageServerHaskell.useCustomHieWrapperPath` path every time before running VS Code by which platform that I use now.

## My current situation

Now, I'm working like this way:

    //"languageServerHaskell.useCustomHieWrapperPath": "${HOME}/hie.bat"
    "languageServerHaskell.useCustomHieWrapperPath": "${workspaceFolder}/hie.sh"

By switching comment out based on the platform that I use now.

## Question

Could you prepare the options for each platform like

    "languageServerHaskell.useCustomHieWrapperPath.unix": "${workspaceFolder}/hie.sh"
    "languageServerHaskell.useCustomHieWrapperPath.windows": "${HOME}/hie.bat"

I know the best way to share the code between Linux and Windows, is that pushing&pulling the code based on a repository, but I usually forget to commit and push...

**Comment by jneira** [comment]
The wrapper extension settings has been removed but the requested feature could be implemented with the `hieExecutablePath` setting

**Comment by jneira** [comment]
@QuietJoon `languageServerHaskell.useCustomHieWrapperPath` no longer exists and the constext has changed a lot since this issue, with automatic dlownload of executables, please open a new issue if you keep havinf problems switching between platforms
