### ISSUE TITLE
How to get coc.nvim port merged cleanly?

### ISSUE THREAD

**Issue by expipiplus1** [haskell/vscode-haskell#169]
I've made a port to coc.nvim: https://github.com/expipiplus1/vscode-hie-server/tree/coc.nvim

I'm certainly no typescript expert, but would really like to merge the support for coc.nvim into master to avoid all the fuss of porting features back and forth. Can any typescript experts lend any advice? 

![I have no idea what I'm doing dog](https://i.kym-cdn.com/entries/icons/original/000/008/342/ihave.jpg)

Some things I noticed:

- There's no `window`, so that prevents quite a few things mapping (things such as the docbrowser) cleanly (these have been disabled for now in my branch).
- The `registerCommand` (or `registerTextEditorCommand` (missing)) commands have a slightly different interface, vscode passes `editor` and `edit` to them, where as the equivalents have to be fetched from the global `workspace` in coc.nvim
- No difference between range and vsrange
- Different modules are used for importing (duh)
- `string`s used instead of `Uri`s

This repository certainly isn't the place for some "compatibility layer", but perhaps if the differences are small enough then this could be done all locally.

**Comment by expipiplus1** [comment]
One thing might be to encourage contributors to make the same change to the coc.nvim branch when making a PR here; definitely not an ideal solution though.

**Comment by expipiplus1** [comment]
Bumped into this "compatibility layer" https://github.com/coc-extensions/coc-fsharp/blob/30b93e1071d87361f5690ddd9fbe4e3a2fca84fb/client/coc_compat.ts

Perhaps we could merge something like this and the fork would just be fiddling with some imports at the top. It would certainly make the rebases I'm doing less painful.

**Comment by fendor** [comment]
@expipiplus1 Is this still something you want to pursue?
