### ISSUE TITLE
Go to library definition

### ISSUE THREAD

**Issue by Swoorup** [haskell/vscode-haskell#192]
Does this extension support viewing library source files, similar to intellij-haskell via `Go To Definition`?

**Comment by Avi-D-coder** [comment]
Not yet. It's blocked on [ghcide integration](https://github.com/haskell/haskell-ide-engine/issues/1416), and then ghcide gaining [support](https://github.com/digital-asset/ghcide/issues/61).

**Comment by jneira** [comment]
Only note that the ghcide integration is being done in haskell-language-server.

**Comment by andys8** [comment]
@jneira could you explain why this is part of haskell-language-server and not ghcide to help with my understanding? What about this issue, where it says it's already jumping somehwhere https://github.com/digital-asset/ghcide/issues/509 ? Thanks :)

**Comment by fendor** [comment]
Haskell Language Server is based on the ghcide fork of mpickering that supports loading multiple components in the same session. This fork is not merged yet, see https://github.com/digital-asset/ghcide/pull/522. As HLS is more experimental, we move faster and break things faster. That is why HLS currently has more features and especially more bleeding edge stuff.

The mentioned issue is about jumping to definitions in the same component, e.g. library component, which already works reliably, afaik.

**Comment by andys8** [comment]
Thank you

**Comment by jneira** [comment]
Thanks for reporting the issue.
It is not implemented yet, the issue in the lsp server backend tracking the feature request is https://github.com/haskell/haskell-language-server/issues/708
