### ISSUE TITLE
CPP extension causes error

### ISSUE THREAD

**Issue by michaelmesser** [haskell/vscode-haskell#228]
With `{-# LANGUAGE CPP #-}` I get `"'cc' failed in phase 'C pre-processor'. (Exit code: 1)"` from the extension. When I remove `{-# LANGUAGE CPP #-}` from my haskell file it works. My program compiles and runs fine.

**Comment by jneira** [comment]
@michaelmesser hi, thanks for the bug report, is this still reproduced with last version of the extencion and haskell-language-server?
It that is the case, could you open a new issue in the haskell-language-server providing the additional information requested in the issue template? https://github.com/haskell/haskell-language-server/issues/new
Thanks!
