### ISSUE TITLE
Adding a package does not resolve an error

### ISSUE THREAD

**Issue by worm2fed** [haskell/vscode-haskell#233]
When I use imports in my code and there are no package in my project two things happen:
1) If I use quick fix (add package as dependency) vscode corrupts the order of lines in package.yaml
BEFORE:
![image](https://user-images.githubusercontent.com/6579275/83729552-73494e80-a650-11ea-92df-ff72a6e61e27.png)

AFTER:
![image](https://user-images.githubusercontent.com/6579275/83729601-82c89780-a650-11ea-8574-0af7cf16428e.png)

and no effect then
2) I still see the error (in first case and if I manually add a dependency)
![image](https://user-images.githubusercontent.com/6579275/83729794-d0450480-a650-11ea-923e-d19b42b46be9.png)

The error occurs till I reopen my workspace

**Comment by fendor** [comment]
Thank you for your bug report!
I am assuming you are using Haskell IDE Engine.
This is a known problem, we currently do not reload the session if there are changes to relevant files such as package.yaml, *.cabal files, etc...
Unfortunately, this will not be solved in Haskell IDE Engine.

The good news is that it is implement in [Haskell Language Server](https://github.com/haskell/haskell-language-server/) and [ghcide](https://github.com/digital-asset/ghcide)! Neither of the projects have feature parity with Haskell IDE Engine, but we are slowly getting there!

**Comment by worm2fed** [comment]
thanks for information

**Comment by jneira** [comment]
Hi, haskell-ide-engine in no longer supported and haskell-language-server still does not have the feature. It is tracked here: https://github.com/haskell/haskell-language-server/issues/155

I hope this bug will be not present when the feature would be added
