### ISSUE TITLE
Provide Vscode Notebook Support

### ISSUE THREAD

**Issue by Matelasse** [haskell/vscode-haskell#234]
Hi. It may be a little early for this issue, but soon (already available in Insiders) Vscode will add API for native notebooks. There's IHaskell kernel available out there to be hooked up with vscode's API, so my feature request would be to connect them up. Python extension is currently adding support for this, and so is Julia (https://github.com/julia-vscode/julia-vscode/pull/980). Haskell Notebooks in vscode will be very nice for existing Haskell developers, and they will be even nicer for Haskell beginners.

**Comment by jneira** [comment]
@Matelasse thanks for the suggestion, has been some time since this so what could be the actual state of the art for this?

**Comment by jneira** [comment]
The api is here https://code.visualstudio.com/api/extension-guides/notebook

**Comment by tittoassini** [comment]
It actually seems to work already.

I installed the Jupyter vscode extension and https://github.com/gibiansky/IHaskell and I can open and execute haskell notebooks in vscode.

Or were you thinking of some form of closer integration?

**Comment by fendor** [comment]
Looks like there is nothing we need to do here. Closing, feel free to reopen if there is something we need to do for IHaskell integration.
