### ISSUE TITLE
Format cabal files

### ISSUE THREAD

**Issue by WillSewell** [haskell/vscode-haskell#241]
It would be nice if this extension could format cabal files with `cabal format`.

Is there a reason (technical or otherwise) why this might not be a good idea?

If you agree that it would be nice to have, it's something I'd be happy to have a go at implementing.

**Comment by fendor** [comment]
It could be a plugin in Haskell Language Server, e.g. [cabal-fmt](https://github.com/phadej/cabal-fmt)
I think `cabal format` itself doesnt do a lot. Also, maybe developers have only stack installed, so it might even not be available.

In my opinion, it would be a very nice addition!

**Comment by WillSewell** [comment]
Ah I had assumed that `vscode-hie-server` called Haskell formatters (brittany, ormolu) directly. Does it invoke the via Haskell Language Server? Either way I think this should be consistent.

**Comment by jneira** [comment]
@WillSewell yeah, the formatting should be added in hls as a plugin. I've added a issue to track it in the hls repo: https://github.com/haskell/haskell-language-server/issues/183

**Comment by bubba** [comment]
Closing since this has been moved to haskell-language-server!

**Comment by berberman** [comment]
cabal-fmt does not seem to export its API to be called on the server side, so I wrote a very simple vscode extension to call it on the command line: https://github.com/berberman/vscode-cabal-fmt

**Comment by jneira** [comment]
some time ago I had the crazy idea of setup a LSP server for cabal with diagnostics, completions, create non existing modules and trigger cabal commands.
crazy indeed

**Comment by ndmitchell** [comment]
I think a Cabal LSP is an inevitability - in the fullness of time - it's just a reasonable amount of work for something that is a much smaller amount of benefit (people don't spend that much time editing .cabal files)
