### ISSUE TITLE
Publish on open-vsx.org / VSCodium support

### ISSUE THREAD

**Issue by mkoloberdin** [haskell/vscode-haskell#250]
Could you please publish the extension on open-vsx.org as well?
See https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by bubba** [comment]
Hi @jaspervdj, could you log into https://open-vsx.org from the haskell GitHub org and create an access token for this? https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#1-create-an-access-token

**Comment by jaspervdj** [comment]
@bubba I tried, but it seems that I can only get an access token for my personal account (`jaspervdj`) and not the Org.  I think what we should do is first have you create the `haskell` namespace, and after that I should be able to claim it using [this procedure](https://github.com/eclipse/openvsx/wiki/Namespace-Access) and grant everyone who needs it access.

**Comment by bubba** [comment]
@jaspervdj just created an access token and went to create the namespace, but apparently it already exists:

```
$ npx ovsx create-namespace haskell -p ...
npx: installed 68 in 4.862s
❌  Namespace already exists: haskell
```

So can we just skip this step and go directly to claiming it? https://github.com/eclipse/open-vsx.org/issues/new/choose

**Comment by jaspervdj** [comment]
@bubba That worked!  I've added you to the `haskell` namespace.  Hopefully that'll allow you to publish this extension.

**Comment by bubba** [comment]
Looks like we can't upload it just yet as the syntax highlighting dependency isn't on open-vsx.org yet, created an issue to track this: https://github.com/JustusAdam/language-haskell/issues/171

**Comment by bubba** [comment]
Apparently open-vsx has already published it on our behalf this week: https://github.com/open-vsx/publish-extensions/commit/ceccdeda114b5aab76f15c5e1a861efc3dda14de

We should still setup travis ci to also publish to open-vsx.org on each tag

**Comment by bubba** [comment]
https://github.com/eclipse/openvsx/issues/159

**Comment by bubba** [comment]
@jaspervdj I thought I used to able to access the settings page of the travis CI for this repo, but looks like I no longer have access. On https://travis-ci.org/github/haskell/vscode-haskell can you add a new secret for your access token/any access token that is in the Haskell namespace? Under the key `OPEN_VSX_ACCESS_TOKEN` so that 2b078fa can pick it up

**Comment by jneira** [comment]
Afaik @fendor already is using the extension in vscodium

**Comment by fendor** [comment]
Yes, I am! Works marvelously!

![codium](https://user-images.githubusercontent.com/8463814/94530533-82758d00-023b-11eb-9d94-2ca988989299.png)

**Comment by jneira** [comment]
Ops, @bubba maybe we stil should add the publishing in ci

**Comment by bubba** [comment]
@jneira I commented out the publishing step just there, I think we need someone from the haskell org to add the `OPEN_VSX_ACCESS_TOKEN` key to travis ci first

**Comment by jneira** [comment]
@jaspervdj could we add the secret key to activate the publishing? thanks!

**Comment by jaspervdj** [comment]
@bubba @jneira Sorry, I completely forgot about this.  I added a secret for `OPEN_VSX_ACCESS_TOKEN` in Travis.  I restricted it to the `master` branch.  Give it a try and let me know if I need to change anything?

**Comment by jneira** [comment]
many thanks and no worries, sure you are very very busy 🙂
