### ISSUE TITLE
VSCode's "Haskell (legacy)" vs "Haskell"

### ISSUE THREAD

**Issue by kirillbobyrev** [haskell/vscode-haskell#260]
Right now the link in this repo points to [Haskell (legacy) extension](https://marketplace.visualstudio.com/items?itemName=alanz.vscode-hie-server) which has `0.2.0` version. IIUC the correct (new) extension is [Haskell](https://marketplace.visualstudio.com/items?itemName=haskell.haskell) (published by "Haskell") since it has the 1.0.0 version but the Legacy version doesn't have any correct pointers and I can't really find any pointers to it in this repo, too, so this isn't really easy for me to understand what to use.

Is the assumption above correct?

**Comment by bubba** [comment]
Yeah your assumption is correct, we should update the README for the legacy extension to point this out. ping @jaspervdj can you update the link to this repo to point to `https://marketplace.visualstudio.com/items?itemName=haskell.haskell`, and update the project description to say "VS Code extension for Haskell, powered by haskell-language-server"?

**Comment by bubba** [comment]
And now that I think about it I don't have access to publish the legacy extension so I think we need to wait till @alanz is back from his vacation before we can update the README

**Comment by jaspervdj** [comment]
@bubba Sure, I've made the updates.

**Comment by bubba** [comment]
@jaspervdj thanks, that was fast!

**Comment by alanz** [comment]
So can we close this issue? Do I still need to do anything?

**Comment by bubba** [comment]
@alanz I just pushed a commit to the legacy branch that adds a note to the README about migrating to the newer extension, could you pull that and make one last publish to alanz.vscode-hie-server? It should be enough to just run `vsce publish minor` and let it handle the tagging + version bumping

**Comment by alanz** [comment]
Do we need to bump the version for this?  Will do so anyway, just in case

**Comment by bubba** [comment]
I think `vsce publish minor` automatically bumps it, but for the legacy extension I guess it doesn't matter much
