### ISSUE TITLE
Posibility to specify binary version

### ISSUE THREAD

**Issue by Truedrog** [haskell/vscode-haskell#266]
Hi,

say, I have this stack.yaml with something like this:

```
resolver: lts-16.5
compiler: ghc-8.8.4
```
It worked fine with 0.2.1 version, but now it does not. How can I point it to download older binaries? [(0.2.1)](https://github.com/haskell/haskell-language-server/releases/tag/0.2.1)

**Comment by jneira** [comment]
There is a config option to set the path to a custom executable: `haskell.serverExecutablePath`. You could use it to point to the version you want.
However, could you describe the problem you have with the newer version?

**Comment by Truedrog** [comment]
The newer version doesn’t have the binary for windows ghc-8.8.4, because of
that vscode plugin could not download it, and I can’t set that it will use
the older version of hls.

**Comment by jneira** [comment]
ok, i will try to upload the executables compiled in my local Windows machine

**Comment by jneira** [comment]
@Truedrog I've uploaded windows executables for 0.2.2 and ghc 8.8.3/8.8.4, could you try again?

**Comment by Truedrog** [comment]
It works. Thanks.
