### ISSUE TITLE
[Feature Request] Restart HLS

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/vscode-haskell#271]
It would be awesome to be able to restart the Haskell Language Server without having to reload the entire window, same as one can restart the TS server.

**Comment by bubba** [comment]
It already exists, try cmd/ctrl-p -> Restart Haskell LSP Server! We should advertise this better in the README

**Comment by wz1000** [comment]
VSCode will also generously restart it for you after a `pkill haskell-language-server`. This can be useful for doing this with an external script, such as one that monitors memory usage or something.

**Comment by GuillaumeDesforges** [comment]
Thanks !
