### ISSUE TITLE
Code evaluation not working

### ISSUE THREAD

**Issue by alienvspredator** [haskell/vscode-haskell#277]
<img width="610" alt="Снимок экрана 2020-08-13 в 19 20 36" src="https://user-images.githubusercontent.com/39991717/90160150-12e63400-dd9a-11ea-97cc-b112476cff89.png">

There is no option to evaluate.

haskell-language-server version: 0.3.0.0 (GHC: 8.8.3)

**Comment by bubba** [comment]
You need to write a doctest style comment above like

```haskell
-- | >>> example
example = 42
```

**Comment by alienvspredator** [comment]
It's working. Thanks
