### ISSUE TITLE
[Feature Request] Checkbox in the setting to disable `auto-downloading/auto-updating`

### ISSUE THREAD

**Issue by Meowcolm024** [haskell/vscode-haskell#281]
I find that (almost) every time the extension launches, it would check for the `latest haskell-language-server release`. However, when the network is not that good, it would fail (as is often the case in mainland China).

So, is there a way to turn off the auto update?

**Comment by bubba** [comment]
Not at the moment, but it would be handy to have a checkbox in the settings to disable the auto-downloading/auto-updating feature
