### ISSUE TITLE
[Feature request] Rename symbol

### ISSUE THREAD

**Issue by liftM** [haskell/vscode-haskell#283]
It would be really useful if this extension provided a "rename symbol" implementation for symbols defined inside my program's code. Is this on the roadmap? If I wanted to contribute this functionality, where should I look to get started?

**Comment by jneira** [comment]
hi, the feature request was done in the repo of the main haskell lsp server impl, haskell-language-server: https://github.com/haskell/haskell-language-server/issues/190
It is closed, as the current idea is to use a plugin using the retrie package to implement renaming: https://github.com/haskell/haskell-language-server/issues/282
So i would investigate the plugin system of hls and retrie: feel free to post any question in the [issue](https://github.com/haskell/haskell-language-server/issues/282)

**Comment by jneira** [comment]
You can track the progress of the renaming feature using retrie in the mentioned issue: https://github.com/haskell/haskell-language-server/issues/282

**Comment by locriacyber** [comment]
Is this feature in this extension?
