### ISSUE TITLE
hlint not working on NixOS 20.03

### ISSUE THREAD

**Issue by lukasstevens** [haskell/vscode-haskell#286]
Setup:
- NixOS 20.03
- VSCode 1.45.0
- stack 2.1.3.1
- haskell.haskell 1.1.0

I have a stack project that contains the following file:
```
f x = if x == [] then True else False
```
This should trigger hlint and suggest that I use `null` instead of `==`; however, hlint does not seem to work within VSCode despite `hlintOn` being enabled by default. When I call hlint from the command line, I get the expected lint. The output trace of the extension does not turn up anything related to hlint.

I have tried hlint installed by stack, hlint installed system-wide and no pre-existing installation of hlint.

**Comment by jneira** [comment]
Hi, i am afraid than hlint support is not yet implemented in the haskell-language-server implementation.
There is a wip [pr](https://github.com/haskell/haskell-language-server/pull/166) to do it though.

**Comment by jneira** [comment]
I am gonna close this one, i hope hlint support will be added soon. Please, follow the mentioned pr for updates.
