### ISSUE TITLE
Projects setting "-dynamic" don't play well with the extension

### ISSUE THREAD

**Issue by LeventErkok** [haskell/vscode-haskell#296]
I've a project that I have to compile as a dynamically loaded library, i.e., with GHC's `-dynamic` flag.

Unfortunately, this doesn't do well with VSCode. I see the following printed in the "PROBLEMS" tab:

```
Program error: 
    Cannot load -dynamic objects when GHC is built the normal way
    To fix this, either:
      (1) Use -fexternal-interpreter, or
      (2) Build the program twice: once the normal way, and then
          with -dynamic using -osuf to set a different object file suffix.
```

Is there a known workaround for this problem?

**Comment by jneira** [comment]
I don't use -dynamic, but just in case, have you tried the first option? you could add as ghc-options in the .cabal file

**Comment by LeventErkok** [comment]
@jneira This seems to solve the issue. Thanks!
