### ISSUE TITLE
Fails to start/activate without internet connection

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/vscode-haskell#298]
### Steps to reproduce

1. Disable internet access (I disable wifi on my laptop)
2. Run command "Developer: Restart Extension Host"

### Result

Error popup saying *Couldn't get the latest haskell-language-server releases from GitHub: getaddrinfo ENOTFOUND api.github.com* and the extension is not started/activated.

### Expected

A warning popup is shown, notifying the user that the server could not be updated, but the current version of the extension is started/activated.

**Comment by jneira** [comment]
Agree, the behaviour should be changed. However once we add an option to disable auto download/update it could be used manually (as a workaround): https://github.com/haskell/vscode-haskell/issues/281
