### ISSUE TITLE
Suggestions above imports cause page scrolling jumps

### ISSUE THREAD

**Issue by robrix** [haskell/vscode-haskell#301]
The suggestions shown above imports get added to the editor when things load, but when there’s an error, they go away. The imports are at the top, so the rest of the file then jumps up and down as they get added and removed, which is distracting and even confusing—I frequently lose my place when this happens and have to rebuild some context—and since it happens a _lot_ as I edit, it’s become quite a noticeable friction.

Can they be cached and only invalidated when the line they relate to is changed/removed? Then the delta would only be one line for most edits, and even then it would only occur when I’m actually working on the import lines themselves (which is _much_ less common).

Additionally, is there any configuration to disable these specific things altogether? I’ve got the corresponding warnings off for good reason, and I frequently click these by accident when trying to just place my cursor. By contrast, I do not wish to disable the suggestions for inserting type signatures above exported bindings, so disabling the editor feature would be too coarse-grained.

**Comment by robrix** [comment]
Separately, but related, the moment of latency between e.g. writing/pasting in an import and the suggestion appearing, or opening a file and all of the suggestions appearing, is also a bit jarring, but I don’t know that there’s much to be done about that.

**Comment by ndmitchell** [comment]
This has been reported and is being discussed at https://github.com/haskell/haskell-language-server/issues/426 - the code lens is generic to all haskell-language-server tools, so let's discuss it there.
