### ISSUE TITLE
Add a list of HLS executable file paths in settings

### ISSUE THREAD

**Issue by berberman** [haskell/vscode-haskell#302]
Although it is convenient for most of us, sometimes it can be noisy. I need switch hls between few versions (dynamic linked / static linked), and hls may not appear in PATH. Opening a project, I will find that the plugin has already started downloading it, before I set the path to hls executable manually, so I have to deleted the downloaded binaries to keep it clean, even if those binaries will not make any difference in runtime.

**Comment by jneira** [comment]
@berberman thanks for the suggestion, it makes totally sense. Fortunately the download is configurable in master, only left publish the extension.
(the pr closed #294, duplicate of this one)

**Comment by berberman** [comment]
Perhaps maintaining a list of hls executables' paths for switching in the settings will be nice. :wink:

**Comment by jneira** [comment]
That would be nice too, please change the title of the issue then (or open a new one, as you wish)

**Comment by fendor** [comment]
Not relevant any more, if still a problem, please open a new issue with a new description.
