### ISSUE TITLE
Failed to download haskell-server: EOF

### ISSUE THREAD

**Issue by DLochmelis33** [haskell/vscode-haskell#305]
Issue Type: <b>Bug</b>

Since I installed the Haskell extension pack, every time VSCode starts, there begins a download of haskell-server, which seemingly completes and then fails with the following message:

Failed to download https://github.com/haskell/haskell-language-server/releases/download/0.5.1/haskell-language-server-Linux-8.6.5.gz:
unexpected end of file

The download starts again from the beggining every time, so I doubt the problem is caused by a broken local file.

Extension version: 1.2.0
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.4.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-7310 APU with AMD Radeon R4 Graphics (4 x 1976)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|6.70GB (0.65GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id fb5e495c-3172-434e-b67e-56ea0dacd2b7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by bubba** [comment]
Just to check, can you `wget`/`curl -O`/download this file ok? Could there be a proxy or firewall on your network thats blocking access to the download?

**Comment by DLochmelis33** [comment]
Nevermind, the other time VS Code was opened the installation completed successfully.
