### ISSUE TITLE
Can't find GHC installed with nix-shell

### ISSUE THREAD

**Issue by philschonholzer** [haskell/vscode-haskell#306]
The Extension is complaining about the GHC not being installed, but it is installed via nix-shell. What am I missing?
Running on Mac OS 10.15.6
Extension: haskell.haskell v1.2.0
GHC Version 8.8.4

<img width="1529" alt="Screenshot 2020-10-13 at 18 32 00" src="https://user-images.githubusercontent.com/7238141/95890847-987b6580-0d84-11eb-8b57-0b54101b1e79.png">

**Comment by jneira** [comment]
Maybe some nix user could help us here, @fendor?

**Comment by fendor** [comment]
I think the environment changes too late. How do you launch vscode?I launch it after direnv has succeededto load the environment in the terminal via `code . `

**Comment by philschonholzer** [comment]
It's working now. Not sure what it was, but after quitting vs code completely (before I was alway just reloading the window) and starting from the terminal via `code .` it started to work. Now it's always working, even when not started from the terminal.
