### ISSUE TITLE
Automatically continue doc comments on new line

### ISSUE THREAD

**Issue by djrenren** [haskell/vscode-haskell#310]
When writing multiline doc comments it would be nice to have the comments already inserted like so:

(cursor position is denoted by the <|>)

```haskell
-- | Multiplies a number by two<|>
timesTwo x = x * 2
```

Then I would press enter and get:

```haskell
-- | Multiplies a number by two
--  <|>
timesTwo x = x * 2
```

Ideally that cursor would be lined up with the first letter in the starting line.

P.S. I'm loving this extension

**Comment by jneira** [comment]
Thanks for your suggestion. In fact there is another similar one: #279 so more reasons to prioritize it.

**Comment by djrenren** [comment]
Oh hey, and it’s an almost identical issue. Thanks for taking the time to respond!

**Comment by jneira** [comment]
I am gonna close this one in favor of the old one, as it has some info about possible solutions, you can track the progress there
