### ISSUE TITLE
Handling of hints is incorrect

### ISSUE THREAD

**Issue by hanjoosten** [haskell/vscode-haskell#311]
I get a red underline, telling me something is wrong:

![image](https://user-images.githubusercontent.com/1159672/96365936-8878d280-1144-11eb-8b50-31607155e433.png)

When I hoover over it, it shows the Hlint suggestion responsible for it:

![image](https://user-images.githubusercontent.com/1159672/96365973-da215d00-1144-11eb-9619-733a6e804989.png)

So far, so good. Notice it mentions that no quick fixes are available.

When I click the line, I get this icon that enables me to show fixes:  

![image](https://user-images.githubusercontent.com/1159672/96366020-32585f00-1145-11eb-88ae-b64e8ace18d5.png)

Now I should be confused. Is there a fix, or isn't there one?
Hoovering on the icon suggest me to click on it, to show fixes:

![image](https://user-images.githubusercontent.com/1159672/96366102-aeeb3d80-1145-11eb-8a05-d593d924be5e.png)

After clicking on it, it shows the fix in an all too small window:

![image](https://user-images.githubusercontent.com/1159672/96366160-215c1d80-1146-11eb-872a-48b7abca6551.png)

When I click on the fix, only part of the suggested replacement gets substituted. This breaks the code!

![image](https://user-images.githubusercontent.com/1159672/96366218-70a24e00-1146-11eb-819e-54a67f4b3a45.png)

The substitution should be done in whole. I can imagine that this has something to do with the newline character, but that is just guessing.

**Comment by fendor** [comment]
I guess you are using Haskell IDE Engine (since, iirc Haskell Language Server has no hlint plugin yet).
If that is so, please note that Haskell IDE Engine is no longer being maintained, and while this clearly is a bug, it won't be fixed anymore.

If my assumption is wrong, please correct me.

**Comment by hanjoosten** [comment]
I don't think I am using Haskell IDE Engine. I have enabled the Haskell extention. Not sure what else it uses under the hood.

![image](https://user-images.githubusercontent.com/1159672/96368268-5f137300-1153-11eb-8c1b-32a2c1921470.png)

**Comment by fendor** [comment]
So what did you install?
It could be that `haskell-linter` is the culprit and "we" (the Haskell Plugin) have nothing to do with it.

**Comment by bubba** [comment]
@hanjoosten Yeah I think this must be coming from the Haskell-linter plugin, I can see where the confusion is coming from. It would be nice if we generated these hints but we don't just yet :)

**Comment by hanjoosten** [comment]
Ah, I see. haskell-linter is the culprit indeed. I just disabled it, and now this behaviour obviously doesn't occur any more. 
It isn't simple for plain mortals like me to see which plugin causes what behaviour ;)

**Comment by jneira** [comment]
For reference the extension will have hlint support once this haskell-language-server pr is merged: https://github.com/haskell/haskell-language-server/pull/166
