### ISSUE TITLE
Multi-Cradle: No Prefixes Matched on new Cabal project

### ISSUE THREAD

**Issue by amyjbrown** [haskell/vscode-haskell#315]
### Issue
I recently built a new project using Cabal with `cabal-build`, and generated a hie.yaml file with Implit-hies `gen-hie`. However, I'm  receiving the error "Multi-Cradle" as shown below.

### System 
Linux Mint

### Error Message
Using the default hie.yaml file made with `hie-yaml`, I had this error
```
ulti Cradle: No prefixes matched
pwd: /home/amy/dev/haskell/expr
filepath: /home/amy/dev/haskell/expr/Setup.hs
prefixes:
("./Main.hs",Cabal {component = Just "Expr:exe:Expr"})
```

I attempted to fix this with the preconfigure hie.yaml file for the extension found here https://github.com/haskell/haskell-language-server/blob/master/hie.yaml.cbl

```
Multi Cradle: No prefixes matched
pwd: /home/amy/dev/haskell/expr
filepath: /home/amy/dev/haskell/expr/Main.hs
prefixes:
("./test/functional/",Cabal {component = Just "haskell-language-server:func-test"})
("./test/utils/",Cabal {component = Just "haskell-language-server:func-test"})
("./exe/Main.hs",Cabal {component = Just "haskell-language-server:exe:haskell-language-server"})
("./exe/Arguments.hs",Cabal {component = Just "haskell-language-server:exe:haskell-language-server"})
("./plugins/default/src",Cabal {component = Just "haskell-language-server:exe:haskell-language-server"})
```

**Comment by fendor** [comment]
The initial output looks fine to me, since we do not support loading `Setup.hs` files. So, that diagnostic is fine. The rest mainly comes from incorrect `hie.yaml` configurations. You can find some documentation for `hie.yaml` here: https://github.com/mpickering/hie-bios/

**Comment by jneira** [comment]
@amyjbrown in addition what @fendor commented i want to note that the `hie.yaml.cbl` is suited only for `haskell-language-server`. Each project nees its own config file with the map between (relative) paths to source files and *components* (libraries, executables, test-suites, etc). You can read more about in the link posted above.

The file generated by `gen-hie` (i assumed you wanted to mean `gen-hie` instead `hie-yaml`) is likely to be correct.

**Comment by jneira** [comment]
I think the issue is not actionable, @amyjbrown thanks for reporting it, if you continue experiencing it please, open a new one in the haskell-language-server issue tracker
