### ISSUE TITLE
Snippets?

### ISSUE THREAD

**Issue by halhenke** [haskell/vscode-haskell#32]
Was wondering if we might want to add some snippets - or is this something that you would rather see in a separate, specific extension?

**Comment by nponeccop** [comment]
Snippets are an optional feature of autocompletion in the Language Server Protocol (https://github.com/Microsoft/language-server-protocol/blob/master/snippetSyntax.md), so it's logically should be a part of this extension.

**Comment by jneira** [comment]
haskell-language-server already does completions at several points, if you miss something please open a new issue in the haskell-language-server issue tracker https://github.com/haskell/haskell-language-server/issues
