### ISSUE TITLE
Trim Hlint diagnostic messages

### ISSUE THREAD

**Issue by emlautarom1** [haskell/vscode-haskell#322]
Hlint diagnostic messages contain the full path of the current file and row:column of the suggestion, with a "Suggestion" prefix. This makes the diagnostic verbose with no real benefit.

This may not affect most users, but since I'm currently using [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens), the result is pretty annoying. See the following example comparing type-check errors and hlint suggestions:

![Screenshot from 2020-11-12 11-32-29](https://user-images.githubusercontent.com/31224949/98953264-3de83d00-24db-11eb-9f5c-7df22b5f15e6.png)

**Comment by ndmitchell** [comment]
I think writing our own Idea to string conversion would make sense. CC @jneira

**Comment by emlautarom1** [comment]
I see that there's been some discussion about this issue in the `hls` repo: https://github.com/haskell/haskell-language-server/issues/553

**Comment by jneira** [comment]
@emlautarom1 the issue was fixed in master by https://github.com/haskell/haskell-language-server/pull/598
could you try that version?

**Comment by emlautarom1** [comment]
@jneira Indeed, the issue was fixed. This is the current output:

![Screenshot from 2020-11-16 15-28-45](https://user-images.githubusercontent.com/31224949/99292788-79a73d80-2820-11eb-93ea-73c1754dae6e.png)

Some context:
- Commit `ecafd3efe9e4fc73f6275db4cfa78e0ea8936106` (output from `git log -1 --format="%H"`).
- Built with GHC 8.8.4, cabal-install 3.2.0.0 on Fedora 33
