### ISSUE TITLE
Unable to type in code editor after installing this extension

### ISSUE THREAD

**Issue by pangwa** [haskell/vscode-haskell#324]
Can't type anything in the code editor after installing this extension. Typing works after uninstalling it.
I'm using the vim extension, not sure whether it's related.

> Haskell Extension: v1.2.0
> 版本: 1.51.1
提交: e5a624b788d92b8d34d1392e4c4d9789406efe8f
日期: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by jneira** [comment]
I suppose you cant write in the editor when the file has a haskell related extension (`.hs`) but no for other file extensions, right?

**Comment by pangwa** [comment]
I can't type in the .hs file editor. But it looks all good now. VSCode and the plugin version are all the same! I installed the haskell language server after reporting this issue, this might be related.
