### ISSUE TITLE
Feature Request: Allow disabling "proceeding with implicit cradle" warnings

### ISSUE THREAD

**Issue by boramalper** [haskell/vscode-haskell#326]
I would love to have an option to be able to disable <q>No cradle found for foo.hs. Proceeding with implicit cradle.</q> warnings that pop every time I am editing a Haskell source file.

Apologies if such a feature already exists, and please let me know if so.

Kindly,
Bora

**Comment by ndmitchell** [comment]
This is being discussed at https://github.com/haskell/haskell-language-server/issues/620

**Comment by boramalper** [comment]
Thanks! Feel free to close this issue. :)

**Comment by ndmitchell** [comment]
Thanks, done so. I wonder about putting some text in the README directing users to make all issues in haskell language server. Or maybe we need to get better at transferring...
