### ISSUE TITLE
executableExists assumes the existance of "which"

### ISSUE THREAD

**Issue by expipiplus1** [haskell/vscode-haskell#327]
If `which` isn't in the PATH it should probably not fail saying that the queried executable isn't available, very confusing!

**Comment by jneira** [comment]
or windows 🤔

**Comment by expipiplus1** [comment]
@jneira I bumped into this in a nix build which didn't list `pkgs.which` as a build input.

**Comment by michaelpj** [comment]
I also just hit this. In my case I was trying to build a docker devcontainer with HLS and hadn't put `which` in there. Spent a good couple of hours tearing my hair out about what was wrong with the PATH until I read the extension source! It's a niche case but quite painful when it comes up :sweat_smile:

**Comment by jneira** [comment]
@expipiplus1 @michaelpj hi! i've prepared a fix with #518, could you have the chance of test the pr vsix to check if it fix the issue in your envs?

https://github.com/haskell/vscode-haskell/suites/4605389050/artifacts/124395850

**Comment by jneira** [comment]
checked manually in wsl

**Comment by expipiplus1** [comment]
thanks @jneira!
