### ISSUE TITLE
"Change all occurrences Ctrl+F2" wreaks havoc for some valid symbols

### ISSUE THREAD

**Issue by szabi** [haskell/vscode-haskell#329]
In particular, for symbols with an `'` in their name.

If I try to rename `someSymbol'`, it will
- only make the name editable up to the `'`, excluding it,
- if there is another symbol `someSymbol` in the source, it will be changed as well.

Using `'` is not uncommon in Haskell.

**Comment by locriacyber** [comment]
Related to #283 .

**Comment by fendor** [comment]
Not our responsibility, feature of Haskell Language Server.
However, issue is likely still relevant, but there are a number of issues in the main repo, see https://github.com/haskell/haskell-language-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22component%3A+hls-rename-plugin%22+
