### ISSUE TITLE
Does not work in 8.10.3?

### ISSUE THREAD

**Issue by KilianSillero** [haskell/vscode-haskell#334]
I just installed haskell and the extension does not work with that version or its my fault?

**Comment by bubba** [comment]
Hi, we don't yet have binaries for 8.10.3 but they should be coming shortly: https://github.com/haskell/haskell-language-server/issues/311

If you change your project to 8.10.2 it should be able to find binaries for HLS

**Comment by jneira** [comment]
@KilianSillero Binaries for ghc-8.10.3 are already available for last hls version
