### ISSUE TITLE
Can not disable snippets of type information when completing code

### ISSUE THREAD

**Issue by pzzp** [haskell/vscode-haskell#339]
![image](https://user-images.githubusercontent.com/21138299/105624412-781b7680-5e5c-11eb-9f42-c1ed236daead.png)

This option doesn't work.

**Comment by berberman** [comment]
The [fix](https://github.com/haskell/haskell-language-server/pull/1195) should be included in hls 0.9.0 release, could you confirm this?

**Comment by pzzp** [comment]
> The [fix](https://github.com/haskell/haskell-language-server/pull/1195) should be included in hls 0.9.0 release, could you confirm this?

I tried it just now, it was indeed fixed.

**Comment by nanikamado** [comment]
I tried but it didn't work. I'm using the prebuilt binary from https://github.com/haskell/haskell-language-server/releases/tag/1.1.0.

![Screenshot_20210415_132319](https://user-images.githubusercontent.com/40970181/114813854-ea617e80-9ded-11eb-86fb-c6df7f941eaf.png)

**Comment by jneira** [comment]
the original config option to disable snippets has been deprecated in the server, we have to publish a new release of the client extension to make available the new config option which will have the same effect
