### ISSUE TITLE
Liquid Haskell: type constructor or class not in scope

### ISSUE THREAD

**Issue by raptazure** [haskell/vscode-haskell#341]
The following code gives error: `Not in scope: type constructor or class ‘Int’. Perhaps you meant ‘Int’ (imported from Prelude)`  while `stack ghci` works fine. The related setting: value of `haskell.liquidOn`  is set to true.
```haskell
{-@ type Pos = {v : Int | 0 < v} @-}

{-@ incr :: Pos -> Pos @-}
incr :: Int -> Int
incr x = x + 1
```
![image](https://user-images.githubusercontent.com/44319278/107226866-a18bf300-6a55-11eb-8740-261f150d34e0.png)

Is there a way to fix this or simply disable the error messages? Thanks for answering!

**Comment by jneira** [comment]
hi, thanks for the bug report, I am afraid liquid Haskell is not supported despite the config option (it was inherited from hie, the previous Haskell LSP backend server)
the support in gold is tracked here: https://github.com/haskell/haskell-language-server/issues/367

**Comment by raptazure** [comment]
> hi, thanks for the bug report, I am afraid liquid Haskell is not supported despite the config option (it was inherited from hie, the previous Haskell LSP backend server)
> the support in gold is tracked here: [haskell/haskell-language-server#367](https://github.com/haskell/haskell-language-server/issues/367)
Oh, thanks. Subscribed to that issue. :)

**Comment by jneira** [comment]
closing this as the progress to add the liquid plugin is tracked in the linked hls issue
