### ISSUE TITLE
docs for "Multi Cradle: No prefixes matched"

### ISSUE THREAD

**Issue by 54696d21** [haskell/vscode-haskell#343]
I'm looking for an explanation what that error message actually means

**Comment by jneira** [comment]
hi, there is no explanation in the lsp server (haskell-language-server) official docs, and maybe it should be included. 
The cause of the error is the module you are loading is unknown for haskell-language-server. It uses an implicit, automatic configuration that works for most cases. Is that message followed by something like: `Proceeding with implicit cradle. You should ignore this message` (see https://github.com/haskell/haskell-language-server/issues/1259 f.e.)?

**Comment by jneira** [comment]
The popup alert has been removed in hls, next hls version will not show it anymore
