### ISSUE TITLE
Fails to load HLS 0.9.0 for GHC 8.10.4 on Darwin

### ISSUE THREAD

**Issue by lylek** [haskell/vscode-haskell#344]
Until recently I was using GHC 8.10.3 on macOS 10.15 with HLS 0.9.0 in VS Code and everything was fine. I upgraded to GHC 8.10.4 and now I get the error:

"haskell-language-server 0.9.0 for GHC 8.10.4 is not available on Darwin"

I checked [the repo for HLS](https://github.com/haskell/haskell-language-server) and it says that 0.9.0 supports GHC 8.10.4. I checked the [releases page](https://github.com/haskell/haskell-language-server/releases) and there is a pre-built binary for macOS with HLS 0.9.0. Which in fact, I was already using.

So, why is it telling me that I can't use it with GHC 8.10.4?

According to the VS Code Haskell extension docs, [it only supports up to GHC 8.10.2](https://github.com/haskell/vscode-haskell#user-content-supported-ghc-versions), which I know isn't right either, since I was using it with 8.10.3.

So, is there some hidden list somewhere that needs to be updated? Is there some way I can get around this in VS Code and force it to use HLS 0.9.0 and ignore the error?

Thanks for your help.

**Comment by jneira** [comment]
Hi, thanks for your bug report. I am afraid that for each version of hls (0.9.0 f.e.) we need a different executable for each supported ghc version. We recently added support for ghc-8.10.4 in hls and only left make a release to generate the binaries this etension downloads.
And yeah we already suppot 8.10.3 since some time ago, docs are outdated

**Comment by lylek** [comment]
OK, thanks for the explanation. How does the extension figure out whether there's an executable available? Is there someplace I could check myself to see whether there's a binary for a particular combination? That way I could check that instead of editing my `stack.yaml` and recompiling and loading VS Code and hoping for the best.

I'm on a development team and we have shifted to GHC 8.10.4. I'm the only one using VS Code so nobody else has a problem with the upgrade and HLS in their editors. I have to revert to 8.10.3 until the binary is available.

**Comment by jneira** [comment]
uh, sorry to hear that, I forgot to add some links in my comment:
- binaries are downloaded from the releases of haskell-language-server: https://github.com/haskell/haskell-language-server/releases/tag/0.9.0
- the issue about adding 8.10.4 was https://github.com/haskell/haskell-language-server/issues/1317

will update docs to link to hls releases firectly

**Comment by RodriguezLucha** [comment]
> OK, thanks for the explanation. How does the extension figure out whether there's an executable available? Is there someplace I could check myself to see whether there's a binary for a particular combination? That way I could check that instead of editing my `stack.yaml` and recompiling and loading VS Code and hoping for the best.
> 
> I'm on a development team and we have shifted to GHC 8.10.4. I'm the only one using VS Code so nobody else has a problem with the upgrade and HLS in their editors. I have to revert to 8.10.3 until the binary is available.

What is the process for downgrading to 8.10.3? Just getting started with Haskell was hoping to use all the nice VSCode features..

**Comment by lylek** [comment]
> What is the process for downgrading to 8.10.3? Just getting started with Haskell was hoping to use all the nice VSCode features..

If you're using Stack, change your resolver version from lts-17.4 to lts-17.2.

**Comment by jneira** [comment]
haskell-language-server-1.0 with ghc-8.10.4 has been released so the extension should start downloading it auto, thanks for the patience!
