### ISSUE TITLE
Jump to definition can't find definitons outside currently viewed file

### ISSUE THREAD

**Issue by greggaree** [haskell/vscode-haskell#347]
I'm using the Haskell Language Server, and I can't jump to definitions in files not being currently viewed. I also can't jump to definitions contained in imported libraries.  I see there is an  [Open issue # 192](https://github.com/haskell/vscode-haskell/issues/192) about this, but it's unclear if the language server resolved this issue. At one point the README.md file had [posted this limitation](https://github.com/haskell/vscode-haskell/pull/238#pullrequestreview-506197430), but now it has been deleted. According to a poster, the haskell language servers support jump to definition, but [they do not do so reliably.](https://github.com/haskell/vscode-haskell/pull/238#issuecomment-645813971)

**Comment by greggaree** [comment]
I can now jump to definitions outside the currently viewed file. Not sure if it was the result of my changes to some files or a previous bad build. However, I am limited to definitions defined in my project.  I still can't jump to definitions in imported libraries. I guess this hasn't been implemented yet. Correct?

**Comment by jneira** [comment]
Thanks for reporting the issue, 
Yeah, it is not implemented yet , the issue in the lsp server backend tracking the feature request is https://github.com/haskell/haskell-language-server/issues/708
