### ISSUE TITLE
Haskell language server 0.9.0 for GHC 8.10.4 not available on Windows

### ISSUE THREAD

**Issue by michaelschufi** [haskell/vscode-haskell#349]
Hi :)

I'm getting the following error when opening VS Code:

`haskell-language-server 0.9.0 for GHC 8.10.4 is not available on Windows_NT`

I have just installed Haskell using the recommended chocolatey package:

`choco install haskell-dev`

What should I do to use the extension correctly?

Edit: I've just seen the discussion in #334. Should I downgrade to GHC 8.10.3 with chocolatey or should I try to upgrade the language server to the 1.0.0 pre-release?

**Comment by jneira** [comment]
Hi, the extension downloads automatically the binaries when the release is definitive (1.0.0 is still a prerelease until we upload some missing binaries)
So you can 
* wait (not so much, i hope we will able to mark it as definitive soon), 
* download the actual binary from the prerrelase and putting in `%PATH%`
* or putting ghc-8.10.3 in %PATH% instead ghc-8.10.4 (not need for a full downgrade, you can change `%PATH%` again to make ghc-8.10.4 the default afterwards)
  * if you still has ghc-8.10.3 from a previous installation of course

**Comment by leiftw** [comment]
> * download the actual binary from the prerrelase and putting in `%PATH%`
I put `haskell-language-server-wrapper.exe` from tag `1.0.0` into `%AppData%\local\bin`, which is on my %PATH%.
I get this on restart of vscode:
![vscode haskell-language-server not available](https://user-images.githubusercontent.com/4135680/109095902-e03fcf80-771c-11eb-963a-12f374693477.png)
What did I miss?

**Comment by konn** [comment]
VSCode Haskell extension uses custom path located under VSCode's globalStorage, outside of %PATH%. You can do one othe following:

* Open VSCode preference, and set HLS's server executable path to where you located downloaded binary (Note: this disables VSCode's automatic download feature; you should empty this setting after 1.0.0 is officially released if you need auto update).
* Or, you can place downloaded binary to VSCode's gloealStorage. It seems it is `C:\Users\USERNAME \AppData\Roaming\Code\User\globalStorage\haskell.haskell` on Windows. You should follow naming convention and perhaps need wrapper as well.
* Wait for 1.0.0 to be officially released.

**Comment by leiftw** [comment]
Thanks for the clarification and quick response!
Ah okay so just to confirm: The system variable PATH that you referenced is completely irrelevant?
I actually also tried putting `haskell-language-server-wrapper.exe` into the extensions' `globalStorage` folder, where the other `*-wrapper`s are - that's how I even got the idea to download the wrapper as opposed to `haskell-language-server-Windows-8.10.4.exe`, which I now also put into that folder. Now I'm back to the old "not available" error.
Maybe `latestApprovedRelease.cache.json` in that folder is the culprit? It's a huge object representing the `0.9.0` release including its assets and the included pull requests and their titles, complete with `:slightly_smiling_face:` and all :D
So I can't easily "fake" this file for the new release by just tweaking the version number.

**Comment by konn** [comment]
Hmm, then it seems it is feasible to specify executable explicitly.

> Ah okay so just to confirm: The system variable PATH that you referenced is completely irrelevant?

Not completely. As settings description of `Sever Executable Path` says:

> Haskell: Server Executable Path
> Manually set a language server executable. Can be something on the $PATH or a path to an executable itself. Works with ~, ${HOME} and ${workspaceFolder}.

So I think it's in the PATH, you can just specify its executable name only.

**Comment by jneira** [comment]
@konn thanks, i thought you only needed the executable in `%PATH%` to make the vscode extension prefer it (i have it in `%PATH%` with the file suffix and the extension does not download it for me :thinking: )

Reviewing the code it seems it looks for the executable in PATH if you dont have the `Server Executable Path` informed:

https://github.com/haskell/vscode-haskell/blob/a25b5fa1276f0e2a47cd204bd430eb41748e7ccd/src/extension.ts#L151

(`findManualExecutable`tries the explicit config option and `findLocalServer` looks in PATH)

https://github.com/haskell/vscode-haskell/blob/a25b5fa1276f0e2a47cd204bd430eb41748e7ccd/src/extension.ts#L92-L115

only if that ways dont work it tries to download the release:

https://github.com/haskell/vscode-haskell/blob/a25b5fa1276f0e2a47cd204bd430eb41748e7ccd/src/extension.ts#L152-L163

@leiftw so i think if you put the `haskell-language-server-wrapper.exe` and `haskell-language-server-8.10.4.exe` (with exactly that name, rename your executable if the actual name does not match) in PATH, it should work.

**Comment by jneira** [comment]
@leiftw And..... hls-1.0.0 has been just released while i was writing the previous comment (:laughing:)  so you dont need an additional setup, remove the `Server Executable Path` value, remove all executables in PATH and restart the vscode 
Sorry for the delay and happy hacking!
