### ISSUE TITLE
Module documentation has broken link "Open on Hackage"

### ISSUE THREAD

**Issue by lykahb** [haskell/vscode-haskell#360]
The link produced by the extension looks like this:
https://hackage.haskell.org/package/aeson-1.4.6.0/docs/html/Data-Aeson-Types.html#t:FromJSON

It is not found because of the spurious /html/. It looks like this error only happens for packages built from the github with a nix override. I suspect that the regular expression in processLink doesn't parse the path correctly.

Local path for a good link
/nix/store/38lc3nvdlxy1n0pfn3ks855nr9njr2c0-ghc-8.8.3-doc/share/doc/ghc/html/libraries/text-1.2.4.0/

Local path for a bad link
/nix/store/bz664jz6k19yp4fhagpg004fnm0wirg2-aeson-1.4.6.0-doc/share/doc/aeson-1.4.6.0/html

**Comment by jneira** [comment]
fixed in #452
