### ISSUE TITLE
haskell-language-server 1.0.0 for GHC 8.0.2 is not available on Linux

### ISSUE THREAD

**Issue by aryzing** [haskell/vscode-haskell#367]
Just installed the extension, and on editor startup I get the error message,

> haskell-language-server 1.0.0 for GHC 8.0.2 is not available on Linux

I'm confused because in the docs it explicitly says that it installs the language server automatically together with the extension. Am I missing something?

**Comment by fendor** [comment]
GHC `8.0.2` is not supported by HLS / vscode-haskell. Either upgrade your ghc, or use a different stack resolver, depending on whether you use plain ghc/cabal or stack.
