### ISSUE TITLE
haskell-language-server not available on Windows_NT

### ISSUE THREAD

**Issue by SimonCockx** [haskell/vscode-haskell#372]
When I install this extension and restart VS Code, this plugin fails with the following notification.

> haskell-language-server 1.0.0 for GHC 8.8.2 is not available on Windows_NT

I am running on Windows 10 and I am using the latest stack version (currently 2.5.1).

I have searched for similar issues, but did not find a solution. Is this a bug? Any fixes?

**Comment by jneira** [comment]
I am afraid that we don't support all ghc versions for Windows, all ghc-8.8 (and ghc-8.10.1 and 2) suffer serious bugs that made very difficult build the binaries. I would suggest you switch to 8.10.4 which is very reliable for Windows
We should update the list of supported ghc versions to note the specific windows ones.

**Comment by SimonCockx** [comment]
Okay, thank you for the quick respone. Indeed, an up-to-date list of supported ghc versions would be useful as long as some are not supported.

**Comment by jneira** [comment]
@SimonCockx i've just reviewed the README and we already have the supported ghc version for os: https://github.com/haskell/vscode-haskell#supported-ghc-versions (btw, 8.8.4 and 8.10.2 are already supported)
