### ISSUE TITLE
VS Code Extension not detected ghc --print-libdir.

### ISSUE THREAD

**Issue by Nagkei10** [haskell/vscode-haskell#375]
I'm using Ubuntu-20.04 with WSL2 and installed it using the Stack installer script.
When I try to start Haskell from WSL bash, it outputs `Couldn't execute ghc --print-libdir` error and Language Server doesn't start.
The `implicit-hie` package and `hie-bios` package have been installed.

**Comment by jneira** [comment]
Hi, thanks for the bug report

> When I try to start Haskell from WSL bash, it outputs Couldn't execute ghc --print-libdir error and Language Server doesn't start.

Could you share the concrete command (with args if any) you are trying to execute and the entire output in the console? is it `code .`?

> The implicit-hie package and hie-bios package have been installed.

Those packages are not stricly needed to use vscode with this extension

**Comment by Nagkei10** [comment]
> Could you share the concrete command (with args if any) you are trying to execute and the entire output in the console? is it code .?

`code`.

**Comment by jneira** [comment]
thanks for the additional info, the error is thrown cause:

# You are using stack and although it downloads and uses ghc, the haskell compiler, stack is not putting it in PATH (so if you run `ghc --version` in a terminal for example, it fails too)
# vscode haskell extension through its lsp server backend (haskell-language-server) needs to have ghc on path to open files that not belongs to any "project". A project is a folder with haskell source files but with `stack` specific config files.
  # It is a known limitation reported here: https://github.com/haskell/haskell-language-server/issues/692

So you can either

* put the ghc used by stack on `$PATH` with `export PATH=$(stack path --compiler-bin --silent):$PATH`
* or create a stack project with `stack init`

**Comment by Nagkei10** [comment]
> or create a stack project with stack init
I tried.

> put the ghc used by stack on $PATH with export PATH=$(stack path --compiler-bin --silent):$PATH

I tried, but it didn't work.
