### ISSUE TITLE
Failed to download haskell-language-server-wrapper-macOS.gz

### ISSUE THREAD

**Issue by Somiona** [haskell/vscode-haskell#381]
```
Couldn't figure out what GHC version the project is using:
Failed to download https://github.com/haskell/haskell-language-server/releases/download/1.1.0/haskell-language-server-wrapper-macOS.gz:
socket hang up
```

I can download the file manually via browser and wget though.
I'm using vscode 1.56.0-insider and MacOS BigSur.

Also, I've tried to put my manually downloaded file to the folder in $PATH, as well as ~/Library/Application\ Support/Code/User/globalStorage/haskell.haskell/, both extracted and original file, but not working.

**Comment by jneira** [comment]
> Also, I've tried to put my manually downloaded file to the folder in $PATH

Hi, thanks for reporting this, just in case note that, to make it work, you have to extract the executable inside the .gz file and put it in path, so running `haskell-language-server-wrapper --version` in a console should work.

> socket hang up

I am afraid that it might be related with your vscode installation/env as the download works in the general case.
We should reproduce the issue and check if [the code that actually downloads the files](https://github.com/haskell/vscode-haskell/blob/master/src/utils.ts#L75) could be improved to handle your case.

**Comment by Somiona** [comment]
Hi, it's working now after I purge the vscode and reinstall it. The problem was not there before I upgrade to that vscode version.
I think you're right the issue is related to vscode installation, since everything's okay before upgrade.
I'm sorry I can't reproduce the issue now.

**Comment by jneira** [comment]
@Somiona nice to know it is working for yuou now (although having to reinstall it)
So i am gonna close this one, as it is not reproducible and it is not directly related with something we can do here. But feel free to reopen or open a new one if it reproduces again
