### ISSUE TITLE
Publishing to vscode/open vsx marketplace has failed for 1.3.0/1.4.0/1.5.0

### ISSUE THREAD

**Issue by jneira** [haskell/vscode-haskell#385]
* https://travis-ci.org/github/haskell/vscode-haskell/jobs/768031592

```
Publishing haskell.haskell@1.3.0...

 ERROR  ﻿{"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"innerException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}

Script failed with status 1
```
//cc @alanz

**Comment by jneira** [comment]
* Last issue about publishing was #260

1. It seems a new token has to be generated by a maintainer of the extension in the vscode marketplace: https://marketplace.visualstudio.com/manage/publishers/haskell
2. Then a maintainer of this repo should  update the secret key `$VS_CODE` in travis configuration (i am afraid i have no admin rights to do it): https://travis-ci.org/github/haskell/vscode-haskell/settings

* I hope @jaspervdj could help us with that (happy to do step 2 if i get permissions to do it)

**Comment by jaspervdj** [comment]
@jneira Sorry, somehow this notification ended up in my spam folder.  I added a new token, please try it out before closing this.

**Comment by jneira** [comment]
Dont worry and many thanks, pushing the tag again

**Comment by jneira** [comment]
@jaspervdj i am afraid the publish step now has failed with another error (only http status this time):
```
Publishing haskell.haskell@1.3.0...

 ERROR  Failed request: (401)

Script failed with status 1
```

**Comment by jaspervdj** [comment]
I set up a new one, try again?  If that doesn't work I'll investigate a bit further what could be happening.

**Comment by jneira** [comment]
@jaspervdj [this time it seems the token is missing](https://travis-ci.org/github/haskell/vscode-haskell/jobs/769167514#L453):
```
error: option '-p, --pat <token>' argument missing

Script failed with status 1
```

**Comment by jaspervdj** [comment]
I added a new token and manually verified it using `vsce login haskell`.  I hope things work now?  If not -- are we sure it's the VSCode marketplace that's broken, and not the Open VSX one?

**Comment by jneira** [comment]
thanks again, afaiu the full log i think the publish step of vscode is not being successful, it is the first publish step
I have to retag the version to take in account recent user requests, after that I will try again and remove the open vscode publishing if it fails again, just in case

**Comment by jneira** [comment]
@jaspervdj 
> are we sure it's the VSCode marketplace that's broken, and not the Open VSX one?

You were right, i didn't interpret the log correctly (tbh i find it a little bit confusing) but https://travis-ci.org/github/haskell/vscode-haskell/jobs/769167514#L404-L408. Sorry for the inconveniences.

It would be great to have the token to publish to open vsx as described here: https://github.com/haskell/vscode-haskell/issues/250#issuecomment-800245717
Thanks in advance again!

**Comment by jneira** [comment]
Last build for 1.4.0 has published the extension to vscode marketplace but failed for open vsx with the same error: https://travis-ci.org/github/haskell/vscode-haskell/jobs/770880194

**Comment by jneira** [comment]
@jaspervdj hi, sorry to have to bother you again but the recent travis-ci.org switch off has affected this repo. The repos has to be migrated to travis-ci.com and they continue offering a free plan there. I dont have admin rights to migrate it.

**Comment by jaspervdj** [comment]
@jneira I enabled this on travis-ci.com, but unfortunately it looks like we're out of credits for haskell/ for the time being; so builds have been disabled.  Are there any plans to move this to a more generous CI runner?  In the short term, I can also ask some funds from Haskell.org to keep this running: it's around $800-1600/year, so a bit expensive if we want to keep this around forever.

**Comment by jneira** [comment]
Thanks for take care! We were thinking to switch to github actions since some time ago, and knowing that we will do asap. However the incoming hls release needs this one so i would try to only being able to make this one which hopefully will be the last one.

**Comment by jneira** [comment]
I've signing up for travis-ci.com and i see this repo in my profile, it has a warning:

Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://travis-ci.com/organizations/haskell/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://travis-ci.com/organizations/haskell/plan?anchor=oss-consumption). 

What id that `Consume paid credits for OSS setting`? could we get free credits though them? If i click in thos links i've got an error in their web, i suppose i dont have permission to access or something

**Comment by jneira** [comment]
the publishing using gha worked as a charm for 1.5.0 so i am gonna close it
