### ISSUE TITLE
Command "haskell.showDocumentation" not working

### ISSUE THREAD

**Issue by oshyshko** [haskell/vscode-haskell#400]
![image](https://user-images.githubusercontent.com/73026/119237539-03c0bd80-bb46-11eb-8e5f-6db1a0ad768c.png)

- Haskell extension 1.4.0
- haskell-language-server version: 1.1.0.0 (GHC: 8.10.4)
- VS Code 1.56.2
- macos 10.15.7
- GHC 8.10.4 (via Stackage lts-17.12)
- Stack 2.7.1

**Comment by skress** [comment]
The problem seems to be the iframe that is used to include the documentation into the webview panel.

See https://github.com/microsoft/vscode/issues/123766#issuecomment-840684139 which states that this case is not supported anymore and https://github.com/microsoft/vscode/issues/121479 for a bit more context.

**Comment by mjhoy** [comment]
Any ideas on this one? I find this was a pretty useful feature.

**Comment by jneira** [comment]
From https://github.com/microsoft/vscode/issues/121479#issuecomment-821740409:

> As far as I know, service worker do not see requests for top level iframe pages (inspector.html in your example). If you are loading local content into an iframe inside a webview, chances are that you should probably just load that content into the webview itself and skip the iframe (and all of the extra stumbling blocks it adds)

> Please try updating your extension to use a different approach that does not rely on loading iframe content with as a webview resource (content inside iframes that are on the same origin as the host webview should still go through the service worker)

It seems we have to replace the existing iframe (i've not checked it though)

**Comment by mjhoy** [comment]
I played around with this and couldn't really get the `webview` to render local documentation satisfactorily — it seems like you can't really have `file:///` links to local resources, you need special `vscode-resource:` links. But I might be missing something.

I'm curious if a PR that simply changed the functionality to open the local file in the user's browser (e.g., `vscode.env.openExternal(uri)` is an acceptable solution? Happy to put something together if so.

**Comment by jneira** [comment]
> 
> 
> I played around with this and couldn't really get the `webview` to render local documentation satisfactorily — it seems like you can't really have `file:///` links to local resources, you need special `vscode-resource:` links. But I might be missing something.

And we could not use those `vscode-resource`'s?

> I'm curious if a PR that simply changed the functionality to open the local file in the user's browser (e.g., `vscode.env.openExternal(uri)` is an acceptable solution? Happy to put something together if so.

Ideally we would want to keep the actual functionality, but well it is broken and we always could switch between internal/extrnal browser by configuration if we recoverthe actual one so 👍

**Comment by mjhoy** [comment]
> And we could not use those `vscode-resource`'s?

Well, I have not really played around with this, but: does that not mean parsing/transforming the HTML of the generated haddock files? And once you follow a link, what then? Or in general any transitive link (say from a referenced css file).

**Comment by jneira** [comment]
This was somewhat fixed by #452 with some caveats but i think we could close this one and open new issues about imrpoving the new implementation
