### ISSUE TITLE
Support for ghc 9

### ISSUE THREAD

**Issue by SimonCockx** [haskell/vscode-haskell#402]
We live in the future: people installing haskell-dev will nowadays get ghc 9.0, and they need to go through a hassle to get this great plugin working. Support for ghc 9 would definitely be a huge user experience improvement.

**Comment by jneira** [comment]
Sure! Unfortunately that task requires a huge effort, not only in haskell-language-server (the lsp server backend gor this extension) itself but in all its transitive dependencies.
The good news are we are makin progress on it and hls has limited support for ghc 9. You will need to build it from source though.
You can track the definitive integration in this issue: https://github.com/haskell/haskell-language-server/issues/297

**Comment by SimonCockx** [comment]
Alright, thanks for the link!

**Comment by jneira** [comment]
We already have (limited) support for ghc-9, including an alert about its limited support, you can track the progress in the mentioned hls issue
