### ISSUE TITLE
Show progress bar when getting GHC version to avoid freezing GUI

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/vscode-haskell#412]
This comment explains the issue: https://github.com/haskell/haskell-language-server/issues/2010#issuecomment-878811658  

In short, the process of getting a project's GHC version when using cabal is as slow as resolving dependencies, which can be really slow (in the provided example it takes a minute). The result is that the user gets no feedback on what is going on, because HLS can't start until we know which GHC version the project uses. Also, the GUI may freeze, and prevent other extensions from starting.

The solution is to display a VS Code "progress popup" while we're trying to get the project's GHC version.

This issue is for tracking the required changes to `vscode-haskell` while the linked issue tracks the potential changes to `haskell-language-server`.

**Comment by jneira** [comment]
Many thanks for opening the issue here, i hope it would not too difficult

**Comment by jneira** [comment]
@runeksvendsen after investigatin the code a little bit i've found that the code getting ghc already tries to do it creating a progress notification:

https://github.com/haskell/vscode-haskell/blob/a09c9be206782ab8e35ffe973eae273d7f15205d/src/hlsBinaries.ts#L105

**Comment by jneira** [comment]
ok, trying to open stack project without the appropiate ghc installed to trigger the slow ghc install, i' ve observed that:
* the extension downloads the wrapper
* but it gets stuck showing the progress of downloading the wrapper at 100% (i checked the wrapper executable already was in the vscode storage folder)
* underneath it calls stack which in turn downloads and install ghc

**Comment by jneira** [comment]
.. and if the wrapper is already downloaded, the code dont show the `Working out the project GHC version` either

**Comment by runeksvendsen** [comment]
@jneira 

> have you come to see that message at some point?

No, I don't recall ever seeing this message.

I have recorded a video of what the problem looks like when opening up VS Code for the project in question. See below. It takes one minute and 10 seconds before the language server is started, without any indication of what's going on before that.

https://user-images.githubusercontent.com/1069247/126747378-c870bca5-a231-4e04-93a9-db017345976c.mov

**Comment by jneira** [comment]
Thanks for checking it out, it seems the code tries to show a progress notificacion in the status bar but it is not working (maybe it did with older versions of vscode? i dont remember see it)

**Comment by runeksvendsen** [comment]
@jneira I only see a progress notification two places in the code, both of which are related to downloading HLS:

https://github.com/haskell/vscode-haskell/blob/a09c9be206782ab8e35ffe973eae273d7f15205d/src/hlsBinaries.ts#L105

https://github.com/haskell/vscode-haskell/blob/b14b3735d4582de485342cc8f5c51b2892caea5b/src/utils.ts#L95

But in my video above HLS isn't downloaded, it's hanging while starting up.

When I run the below command (in [this](https://github.com/obsidiansystems/cardano-node/tree/wip-voltaire-prototype-integration-v3) repo)

```
/Users/rune/Library/Application\ Support/Code/User/globalStorage/haskell.haskell/haskell-language-server-wrapper-1.2.0-darwin
```

it hangs for about a minute with the following output:

```
Found "/Users/rune/Obsidian/iohk/code/os-voltaire-fork/cardano-node/hie.yaml" for "/Users/rune/Obsidian/iohk/code/os-voltaire-fork/cardano-node/a"
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.2.0-darwin) Version 1.2.0.0, Git revision be2071e985cb417f984ab00a1aad76dee02d6d0b (dirty) x86_64 ghc-8.10.4
Current directory: /Users/rune/Obsidian/iohk/code/os-voltaire-fork/cardano-node
Operating system: darwin
Arguments: []
Cradle directory: /Users/rune/Obsidian/iohk/code/os-voltaire-fork/cardano-node
Cradle type: Cabal

Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.10.4


Consulting the cradle to get project GHC version...
```

It looks like this is the reason VS Code is hanging: since `haskell-language-server-wrapper` is slow to start up because getting the project GHC version for cabal requires doing dependency resolution first (which can be slow).

Perhaps we need to add a progress dialog for _Starting HLS_?

**Comment by jneira** [comment]
The process is:
* download haskell-language-server-wrapper, it shows the download progress notification for me, maybe you already has it downloaded. It uses `downloadTask`
* call `haskell-language-server-wrapper --project-ghc-version` to get the project ghc version. This should show `'Working out the project GHC version` but i doesnt
* download `haskell-language-server-$hlsVersion}-${ghcVersion}` using `downloadTask`. It shows the download progress notificaction too for me
* run it

So the key is making   `'Working out the project GHC version` works
