### ISSUE TITLE
Gray on imported but not used methods or modules

### ISSUE THREAD

**Issue by nodew** [haskell/vscode-haskell#432]
It's a feature request. I'm not sure if it's supported by HLS side or not. With this feature, people can easily clean up unused imports when refactor codes.

**Comment by jneira** [comment]
Hi, thanks for opening the issue. The pure syntactic coloring is part of the dependant extension `justusadam.language-haskell`. Your request is about a semantic based coloring so it would be out of scope of that one.
This extension (via the languga server) mark the imported but not used modules and definitions with a yellow squiggle and it even suggests remove them automatically:

![imagen](https://user-images.githubusercontent.com/54035/128665271-1fa000f7-d1a6-4209-b331-589085ee4341.png)

To activate those "diagnostics" and code refactorings you have to enable warnings in the compiler (as the language server needs them). To do so you have to could add `ghc-options: -Wall`. It will enable a useful set of compiler warnings with the unused modules and definitions included.
