### ISSUE TITLE
Disabling "explicit imports code lenses" does not seem to work

### ISSUE THREAD

**Issue by edsko** [haskell/vscode-haskell#438]
When "Enables explicit imports code lenses" is enabled, the import section of my example looks like

![image](https://user-images.githubusercontent.com/935288/129549747-8bbbe493-473d-4001-b998-0a538beccc69.png)

After disabling, it looks like

![image](https://user-images.githubusercontent.com/935288/129549785-64781bf0-37be-437e-a7e7-53cfcf873add.png)

I'd not expect to see any import lenses anymore (but maybe I'm misunderstanding the setting?), but although _some_ import lenses are gone, but all are.

I initially reported this as as a bug against HLS itself (https://github.com/haskell/haskell-language-server/issues/2098) but I guess it's a vscode integration problem, not a HLS problem.

**Comment by jneira** [comment]
hi, thanks for the bug report, did you see https://github.com/haskell/haskell-language-server/issues/2098#issuecomment-899609254 in the original issue?

**Comment by alanz** [comment]
There are two import lenses, one called refine imports. I recently managed to kill it in emacs with https://github.com/emacs-lsp/lsp-haskell/pull/130.  The setting path is "haskell.plugin.refineImports.globalOn".

**Comment by jneira** [comment]
@edsko there are two plugins emitting code lenses, you can disable last ones as suggested by @alanz

**Comment by edsko** [comment]
Ok, great! Thanks for the responses. Just in case somebody else comes across this issue: what this means is that this particular plugin cannot (yet) be disabled using the vscode Haskell extension settings, but if you open `settings.json` and add

```
    "haskell.plugin.refineImports.globalOn": false,
```

the plugin is disabled.

**Comment by jneira** [comment]
hmm there is no config to disable it? it should
