### ISSUE TITLE
Support 8.10.6

### ISSUE THREAD

**Issue by hojberg** [haskell/vscode-haskell#447]
Can we add support for 8.10.6 https://www.stackage.org/lts-18.8? (Happy to help, but don't know where to look)

**Comment by jneira** [comment]
@hojberg hi! thanks for note it, we already are working on it: https://github.com/haskell/haskell-language-server/pull/2109
The next release will have it. In the meanwhile you could build haskell-language-server from source.

**Comment by jneira** [comment]
With the new hls release we have support for 8.10.6 and 8.10.7!
