### ISSUE TITLE
Evaluate file

### ISSUE THREAD

**Issue by dustinlacewell** [haskell/vscode-haskell#451]
I was surprised to find there is no feature for just evaluating the current file. Would that be a useful feature? I am just learning Haskell and I think it could be. Maybe I missed it.

**Comment by jneira** [comment]
Hi, welcome to haskell and thanks to open the issue, could you elaborate what do you mean with "evaluate the current file"? opening it in a repl/ghci session?
The ide now loads the file with ghc and provide lot of info as diagnostics. Otoh you have available the [eval plugin](https://github.com/haskell/haskell-language-server/tree/master/plugins/hls-eval-plugin) to evaluate expressions in the module context: 

![Eval](https://github.com/haskell/haskell-language-server/raw/master/plugins/hls-eval-plugin/demo.gif)

**Comment by dustinlacewell** [comment]
Right, I knew that you could evaluate code within comments. But why not the whole file? Why not just throw a bit of code into a file and evaluate it it (output in the vscode output pane)? I guess I'm confused why it is limited to just within comments of a file.

**Comment by konn** [comment]
It seems you have some misconceptions about Haskell modules. Every Haskell program file is a mere module.
Haskell modules consist solely of declarations of functions or types - hence, in Haskell, "evaluating whole the Module" doesn't make sense, as opposed to scripting languages such as Ruby or Python.

Or, perhaps you might want *execute* the Main module. In Haskell, the module is marked as *main module* and provides `main` function, then Haskell treats it as the entry point of the program, as in C or Rust. If you want to simulate this behaviour, you can just invoke `main` function in Eval comment or REPL prompt.

And indeed, Eval Plugin (eval-in-comment feature as described above by @jneria) loads an entire module and evaluate the expression in that context. This is essentially the same as loading modules within GHCi (interactive REPL) and evaluating code fragments in the prompt.

Indeed, there has long been a plan to support a feature to open REPL process using Language Server's context as a separate process - see haskell/haskell-language-server#477 and #450.
Meanwhile, you can use either Eval-in-comment, or open a separate terminal in VSCode and invoke ghci manually to load the modules in REPL. Note that the latter approach doesn't share the internal state with Language Server, so it can have stale state compared to the Language Server and you have to reload module manually. Or, perhaps you could simultaneously use [ghcide](https://github.com/ndmitchell/ghcid ) in addition to HLS, which saves manual reloads.

**Comment by dustinlacewell** [comment]
> Or, perhaps you might want execute the Main module.

Yeah that. Invoking `main` from a comment is not bad at all I'll do that. Thank you for the detailed response, I appreciate that.
