### ISSUE TITLE
Looking for hls old versions compatibles with the requested ghc version

### ISSUE THREAD

**Issue by jneira** [haskell/vscode-haskell#454]
* hls is deprecating support for ghc versions (see https://github.com/haskell/haskell-language-server/issues/2168)
* but we could continue supporting it with older hls version
* to do it automatically when downloading the executable we should look for an appropiate hls version in older releases
* it could be done on the fly but if we teach the extension the matrix of hls/ghc versions, we could go directly for the desired one and we could improve error messages when a ne ghc version is not supported at all (see #453)
*  the extension should show an alert message (maybe a confirmation message?) when downloading and old version (as it will not have the same feature set and could suffer some bugs)

**Comment by Ailrun** [comment]
One other problem is when a user use stack; Depending on projects snapshot, it will use different GHC versions, so it's not possible to install HLS before starting a specific project

**Comment by Ailrun** [comment]
Ah by "not possible ... before starting a specific project", I mean even when a machine already has a HLS binary, it still needs to check the GHC used in the project and download older/newer HLS

**Comment by cdsmith** [comment]
Yes, stack is awkward.  It's actually hie-bios, which is part of HLS, that finds the stack configuration, right?  Even worse, if the project uses multi-cradle, then there may be different stack.yaml files, and different parts of the project may be built with different GHC versions.  There might just not even be an HLS version that is compatible with the full set of GHC versions in use for the project.  :(

So the options seem to be:

1. Duplicate the logic to find all of the `stack.yaml` files in the VSCode extension.  Solve (in some sense) for a version of GHC that is supported by all of the `stack.yaml` files.  In case of failure of the solver, warn and fall back to the most recent HLS?  Note that "solve" might mean something trivial, like just giving up if there's more than one snapshot or more than one version of GHC involved.
2. Give up on stack.  Just match the GHC in the path, and fall back to the most recent GHC if there's none in the path.

Note that this isn't just a concern for stack.  There are also nix builds where there's no GHC in the path, and the version of GHC used for building depends on resolving a bunch of nix files, which is done via `hie-bios` configuration.  This is another case where there's no guarantee that one version of GHC will be enough to build the whole project.

**Comment by jneira** [comment]
> Can we ask haskell-language-server-wrapper which GHC is will infer

yeah `haskell-language-server-wrapper --project-ghc-version`

> Determine which HLS version the wrapper script would run, preferably by downloading the latest HLS and asking it if possible.

Not sure if i am understand it fully but the extension already does something similar:

1. Downloads haskell-wrapper-server
2. Execute `haskell-language-server-wrapper --project-ghc-version` inthe prject root dir
3. Download the hls executable suited for that version from the *last* hls github release

We "simply" have to change it to download from older releases if the ghc is not supported by the last one

**Comment by cdsmith** [comment]
Okay, great!  Sounds like a good plan, then, and stack and nix builds will not be broken (unless they already were)

**Comment by sweirich** [comment]
I just wanted to note that I this issue is important to me. For simplicity, I'm using stack for my class this semester and have configured all course projects and autograders to use the same lts. In August, I selected the most recent lts that worked with all of the tools that I wanted to use (hlint, ormolu, vscode) on all platforms. However, in November, haskell-language-server dropped support for GHC-8.10.4. I'd really like to be able to use vscode with older versions of GHC when necessary, without resorting to the workarounds in #504.

**Comment by sweirich** [comment]
Maybe Haskell Foundation can help? I'll also add an issue to https://github.com/haskellfoundation/tech-proposals so that they know about it.

**Comment by mduerig** [comment]
Created  PR  #506 to start addressing this.
