### ISSUE TITLE
How to change the GHC version the extension uses for stand alone files

### ISSUE THREAD

**Issue by h2df** [haskell/vscode-haskell#455]
Hi,
Currently I'm using an unsupported verion of stack ghc so I get this error message:

> haskell-language-server 1.3.0 for GHC 8.10.6 is not available on Windows_NT. See the list of supported versions here

I'm new to the language and the tool chain so I wonder where the extension is picking the GHC version from. I would guess it's the global configuration at `C:\sr\global-project\stack.yaml`. But changing the resolver value in that file to 8.10.5 is not picked by the extension.

Changing my stand alone files into a project fixes the issue, the project stack.yaml (with supported resolver version) will be horored. But as a beginer I'm would love to avoid dealing with the hassle of all the meta files in a project.

Is there a way to make the extension pick up a GHC version I specify for stand alone files, so that I can give it a version it supports?

Thanks!

**Comment by jneira** [comment]
Hi, thanks for your question, whic might help other ones. 
For now the ghc used for standalone files is the ghc in `$PATH`, so change it should work. Ideally opening standalone files should be consistent with projects and we have an issue to track it: https://github.com/haskell/haskell-language-server/issues/692

**Comment by h2df** [comment]
Thanks a lot for the information.
