### ISSUE TITLE
HLS will not update to latest if have local in PATH

### ISSUE THREAD

**Issue by soiamsoNG** [haskell/vscode-haskell#456]
HLS will not update to latest if have local in PATH

if we could prompt and let user to select the behavior

**Comment by jneira** [comment]
hi, thanks for the suggestion. I think it would be disturbing for users wanting to use an older version of hls in PATH being prompted to install the new one. So it should be a configuration option, maybe preserving the actual behaviour as default.

**Comment by soiamsoNG** [comment]
but current version ignore the configuration option of the Update Behavior

**Comment by soiamsoNG** [comment]
Sorry mistake close, I will write a PR, because keep-up-to-date behavior, ignore when have HLS in local PATH (even Server Executable Path not set)

**Comment by jneira** [comment]
hmm thanks, but you have to consider the extension prefers the executable in PATH over the downloaded ones

**Comment by fendor** [comment]
irrelevant now, HLS binaries are managed by ghcup now
