### ISSUE TITLE
Automatic downloading of macos arm (aarch64/M1) hls version 

### ISSUE THREAD

**Issue by jneira** [haskell/vscode-haskell#458]
* We dont take in account the architecture when looking for hls artifacts
* A possible approach could be looking for a specific arch and fallback to the default artifact without it
* We should be able to get the arch where the vscde extension is being used and translate it to a common identifier, ghc, ghcup and cabal uses `aarch64`

**Comment by goldfirere** [comment]
This bug has been biting me for several weeks -- but I didn't know it! Even if fixing this is hard, would it be at least possible to issue an error to the user letting them know that VSCode won't work properly on ARM?
