### ISSUE TITLE
Passing extra command line arguments to haskell-language-server

### ISSUE THREAD

**Issue by cdsmith** [haskell/vscode-haskell#462]
I find myself in a situation where I'd like to limit the memory usage of haskell-language-server, because it grows over time and ultimately makes the machine unusable if I leave it running too long.  Basically, I want to pass `+RTS -M10G` to `haskell-language-server`.  Unfortunately, it appears I can't add command line arguments in the option for the server executable, and I don't see another way to accomplish it.

I would like an option that allows adding arbitrary command line arguments to `haskell-language-server`.  I don't think limiting memory usage is, itself, important enough to be worth an option, so generic command line args would be better.

**Comment by jneira** [comment]
Thanks for the suggestion, it makes total sense and other vscode extensions allow something similar.
Relateed #214 as other way to alter the behaviour of the lsp server
