### ISSUE TITLE
Version 1.7.0 seems broken (for Ubuntu 20.04)

### ISSUE THREAD

**Issue by yihozhang** [haskell/vscode-haskell#468]
Hello developers,

Just a heads-up that it seems version 1.7.0 is broken in my environment, which is a freshly installed Ubuntu 20.04 VM.  The error message is something as follows:

```
Invalid argument `'

Usage: haskell-language-server-1.4.0-linux-8.10.7 [--version | 
                                                    --numeric-version | 
                                                    --probe-tools | 
                                                    --list-plugins | 
                                                    --print-cradle | 
                                                    [COMMAND | --lsp | 
                                                      FILES/DIRS...] [--cwd DIR]
                                                    [--shake-profiling DIR] 
                                                    [--test] [--example] 
                                                    [-d|--debug] 
                                                    [-l|--logfile LOGFILE] 
                                                    [-j NUM] 
                                                    [--project-ghc-version]]
  Used as a test bed to check your IDE Client will work
[Error - 5:27:41 PM] Connection to server got closed. Server will not be restarted.
```

It takes me an hour to figure this out since I feel I must miss something as this is just a very standard setup. Then I realized the plugin just released a new version, so there may be something wrong with the new version. I switched back to 1.6.1 and it's working again. I think this new release may confuse other users as well.

**Comment by Wybxc** [comment]
I met the same problem on Windows 10.

**Comment by theqp** [comment]
I have the same problem on Arch Linux + VSCodium

**Comment by sumo** [comment]
Same issue on WSL Debian 10. Rollback to 1.6.1 starts working again.

**Comment by berberman** [comment]
I'm able to reproduce and I believe it's related to #464. Hopefully #469 can fix the issue.

**Comment by jneira** [comment]
@sumo @theqp @yihozhang @Wybxc thanks for reporting and confirming the bug, the new 1.7.1 release should fix the issue
