### ISSUE TITLE
Show references shows symbol definition

### ISSUE THREAD

**Issue by yaitskov** [haskell/vscode-haskell#497]
Hi,

I just installed vscode and the extension.
It is looks great after Emacs ;), but I noticed a spot for improvement.

Let's say a cursor on a name of defined function.
I want to see where the function is used and press F12 or Ctrl+F12.
Results are shown, but not in the best form: all items on the list of files with references are collapsed excepting the file where function is defined, while the files where the function is used are collapsed. I would like to expand all results and maybe collapse file with function definition if there is no references to it within the file (i.e. function signature and export in module don't count).

With current behavior I need to do extra clicks every time I do reference search.

**Comment by jneira** [comment]
Hi! thanks for the suggestion, i am afraid that afaik the behavior belongs to vscode itself and no the extension or the lsp server.
I've search for `references` in the vscode settings and i found `editor.gotoLocation.multipleReferences` amongs others. Maybe changing it or another related one could improve the feature for you.

**Comment by jneira** [comment]
Hi, will close as afaics the behaviour belongs to vscode itself and no the extension, feel free to reopen if you thinks otherwise, thanks!
