### ISSUE TITLE
How to navigate to next/previous block with same indent

### ISSUE THREAD

**Issue by yaitskov** [haskell/vscode-haskell#498]
This shortcut should help with jumping across cases of long functions.

```
data D = A | B | C

f :: D -> String 

f A = "A"
f B = ...
f C = ...

```

Body for every case often has hundreds of lines with possible `where` sections - it is hard to reach next case with existing navigation actions.

Same is applicable for lambda cases.

```
   \case 
     A ->
     B ->
     ...
     Z ->
```

and lets with multiple bindings where these bindings span many lines.

```
 let a = ...
               ...
                  ...
      b = ...
               ...
                  ...
      ...
      z = ...
               ...
                  ...
```

It would be cool jump between a b ... z with a bunch of key strokes.

**Comment by jneira** [comment]
Hi, thanks for the suggestion. This is another thing that belongs to the editor itself and not the extension. Extension have some points where they can contribute, changing the editor behaviour but it is limited, unlike emacs, where you have full control over all the editor features.

Looking in the vscode documentation i've found [a way to navigate top level definitions](https://code.visualstudio.com/docs/editor/editingevolved#_breadcrumb-keyboard-navigation): `ctrl-shift-.`

![imagen](https://user-images.githubusercontent.com/54035/141172768-555badba-45eb-4afa-bcb0-c0123df3f94a.png)

Navigation is oriented to editor symbols, and they are provided by the lsp server. So maybe we could provide symbols for named subexpressions in the`let`/`where` case.

But i've found nothing about blocks with the same ident.

**Comment by jneira** [comment]
It seems an extension can do something similar! Take a look to https://marketplace.visualstudio.com/items?itemName=TonyMalykh.indent-nav

**Comment by jneira** [comment]
I think it makes sense to have features nos haskell specific in separate extensions, so at firs i would say that we should not replicate the feature here. Feel free to reopen the issue if you think otherwise
