### ISSUE TITLE
Error getting the server executable: serverExecutablePath is set to "haskell.serverExecutablePath": "/Users/mukhammaddiyor/.local/bin/haskell-language-server-macOS-8.10.5" but it doesn't exist and it is not on the PATH

### ISSUE THREAD

**Issue by AlijonovMukhammaddiyor** [haskell/vscode-haskell#505]
Hello!

# I am using macOS m1 chip

I have been trying to install Haskell for two days and have not succeeded. I am running the terminal using Rosetta and could install GHCUP with HSL and stack.

However, when I install Haskell (Haskell language support powered by the Haskell Language Server) plugin on vscode and change settings to 
"haskell.serverExecutablePath": "/Users/mukhammaddiyor/.local/bin/haskell-language-server-macOS-8.10.5", 
I am constantly getting the above error.

Can someone help me?

**Comment by jneira** [comment]
Issue transferred to the vscode extension repo

**Comment by jneira** [comment]
@AlijonovMukhammaddiyor did you get to make hls working? afaik nowadays ghcup is able to download a hls version which works in arm based chips on macos

**Comment by fendor** [comment]
Probably not relevant any more, re-open if you feel there is something we can do.
