### ISSUE TITLE
[client][ERROR] No binary haskell-language-server-Windows-8.10.4.exe found

### ISSUE THREAD

**Issue by wclr** [haskell/vscode-haskell#513]
This is a message I get the output:
```
[client][ERROR] No binary haskell-language-server-Windows-8.10.4.exe found in the release assets: haskell-language-server-1.5.1-src.tar.gz,haskell-language-server-FreeBSD-1.5.1.tar.xz,haskell-language-server-Linux-1.5.1.tar.gz,haskell-language-server-Linux-8.10.5.gz,haskell-language-server-Linux-8.10.6.gz,haskell-language-server-Linux-8.10.7.gz,haskell-language-server-Linux-8.6.5.gz,haskell-language-server-Linux-8.8.3.gz,haskell-language-server-Linux-8.8.4.gz,haskell-language-server-Linux-9.0.1.gz,haskell-language-server-Linux-aarch64-1.5.1.tar.xz,haskell-language-server-Linux-armv7-1.5.1.tar.xz,haskell-language-server-macOS-1.5.1.tar.gz,haskell-language-server-macOS-8.10.5.gz,haskell-language-server-macOS-8.10.6.gz,haskell-language-server-macOS-8.10.7.gz,haskell-language-server-macOS-8.6.5.gz,haskell-language-server-macOS-8.8.3.gz,haskell-language-server-macOS-8.8.4.gz,haskell-language-server-macOS-9.0.1.gz,haskell-language-server-macOS-aarch64-1.5.1.tar.xz,haskell-language-server-Windows-1.5.1.tar.gz,haskell-language-server-Windows-8.10.5.exe.zip,haskell-language-server-Windows-8.10.6.exe.zip,haskell-language-server-Windows-8.10.7.exe.zip,haskell-language-server-Windows-8.6.5.exe.zip,haskell-language-server-Windows-8.8.4.exe.zip,haskell-language-server-Windows-9.0.1.exe.zip,haskell-language-server-wrapper-Linux.gz,haskell-language-server-wrapper-macOS.gz,haskell-language-server-wrapper-Windows.exe.zip,SHA256SUMS
```

Some versions ago (of Haskell language support extensions) it was working.

### Your environment

Which OS do you use:
Windows 10

### Include debug information

<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the contents of extension specific log, you can check instructions about how to find it [here](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
Extension log:
</summary>

```
<paste your logs here>
```
</details>

**Comment by jneira** [comment]
Hi, thanks for reporting the issue, unfortunately last hls version 1.5 does not support ghc-8.10.4. The readme is outdates but it notes:

> The exact list of binaries can be checked in the last release of haskell-language-server: https://github.com/haskell/haskell-language-server/releases/latest
> You can check the current GHC versions support status and the policy followed for deprecations [here](https://haskell-language-server.readthedocs.io/en/latest/supported-versions.html).

We are about to release an extension version which will use automatically the newer hls version supporting your ghc: https://github.com/haskell/vscode-haskell/pull/506 and there are some workarounds described here: https://github.com/haskell/vscode-haskell/issues/504

**Comment by jneira** [comment]
I've updated the supported ghc versions with https://github.com/haskell/vscode-haskell/pull/514

**Comment by wclr** [comment]
If I have updated ghc to 8.10.7:

![image](https://user-images.githubusercontent.com/736697/144748925-5e5129e7-e767-4139-a020-3378e4bfeaf8.png)

why do HLS still error about 8.10.4?

**Comment by jneira** [comment]
are you using stack for build the project you want to load in vscode? it it is so you will have to update the resolver in the stack.yaml file

**Comment by wclr** [comment]
Right, thanks, forgot to update the repo. I believe this can be closed.
