### ISSUE TITLE
Stack New Projects Crash HLS

### ISSUE THREAD

**Issue by erichulburd** [haskell/vscode-haskell#522]
### Your environment

OSx Mojave 10.14.6

### Steps to reproduce

* [Install the latest, or upgrade to latest stack](https://docs.haskellstack.org/en/stable/install_and_upgrade/)
* [Install the latest or upgrade to latest ghcup](https://www.haskell.org/ghcup/)

```
$ stack upgrade
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
$ ghcup upgrade
$ ghcup --version
The GHCup Haskell installer, version v0.1.13
$ ghcup install hls
[ Warn  ] HLS ver 1.0.0 already installed; if you really want to reinstall it, you may want to run 'ghcup rm hls 1.0.0' first
$ stack new my-new-project
```

Then open my-new-project in VSCode.

### Expected behaviour

The language server should not crash with error `Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined`.

### Actual behaviour

VSCode notification pops up:

```
The Haskell my-new-project server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

Note, that if I just write a single Haskell script that does not declare any modules, then the VSCode extension works find (syntax highlighting, fix suggestions, go to def, etc).

### Include debug information
Execute in the root of your project the command `haskell-language-server-wrapper --debug .` and paste the logs here (you can find the executable location [here](https://github.com/haskell/vscode-haskell#downloaded-binaries)):

<details>
<summary>
Debug output:
</summary>

```
Module "/Users/user/Code/my-new-project/a" is loaded by Cradle: Cradle {cradleRootDir = "/Users/users/Code/my-new-project", cradleOptsProg = CradleAction: Stack}
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.0.0.0, Git revision 4cd1cf934638881e52b3eba9f70157a4b799c0e9 (dirty) x86_64 ghc-8.10.4
Current directory: /Users/users/Code/my-new-project
Operating system: darwin
Arguments: ["--debug","."]
Cradle directory: /Users/users/Code/my-new-project
Cradle type: Stack

Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.7.3
ghc:            8.10.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.10.7
haskell-language-server exe candidates: ["haskell-language-server-8.10.7","haskell-language-server-8.10","haskell-language-server"]
Cannot find any haskell-language-server exe, looked for: haskell-language-server-8.10.7, haskell-language-server-8.10, haskell-language-server
```
</details>

Paste the contents of extension specific log, you can check instructions about how to find it [here](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
Extension log:
</summary>

```
[2022-01-10 09:11:21.264] [renderer3] [error] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at H (/Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1129652)
	at /Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1135046
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (/Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1135038)
	at /Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1061226
	at async s.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:87704)
[2022-01-10 09:11:26.481] [renderer3] [error] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at H (/Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1129652)
	at /Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1135046
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (/Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1135038)
	at /Users/user/.vscode/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1061226
	at async s.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:87704)
```
</details>

**Comment by fendor** [comment]
It looks like you have an old HLS version installed. (Ghcup logs hint at 1.0.0). Try uninstalling the old version and make sure you have the latest version installed (iirc 1.5.1)

**Comment by jneira** [comment]
@erichulburd hi, thanks for the bug report. Some notes about the info:
* hls last version is 1.5.1, but ghcup is reporting 1.0.0 which is pretty old
* `haskell-language-server-wrapper --debug .` does not find the `haskell-language-server` main executable but it should be installed by ghcup
* the extension log is not the one named `Extensions` but `Haskell(project)`:

![imagen](https://user-images.githubusercontent.com/54035/148841579-705263d5-f5c3-4ec9-a9ba-27918b8d75c5.png)

So despite the error shown in the extension logs i guess the ghcup installation is not correct so i would do the suggested `ghcup rm hls 1.0.0` followed by a `ghcup update && ghcup install hls` (it should install the last version 1.5.1)

**Comment by erichulburd** [comment]
Yes, indeed, the problem was my ghcup installation. I had a number of issues re-installing it, and I don't remember how I originally installed it, but ultimately this is how I got to a good state:

```
rm -rf $HOME/.ghcup
```

Then the install instructions for ghcup failed:

```
$ curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```

so I manually downloaded https://get-ghcup.haskell.org.

```
chmod +x $HOME/Downloads/install-ghcup.sh
$HOME/Downloads/install-ghcup.sh
```

I selected yes to re-install stack. I uninstalled and reinstalled the VSCode extension and modules now load properly.

I appreciate your response! I'll report these ghcup issues in its repo as well.

---

For reference, below are additional issues I had with ghcup upgrade

ghcup does not upgrade from 0.1.13 even though the latest is [0.1.17](https://downloads.haskell.org/~ghcup/0.1.17.4/):

```
$ ghcup upgrade
$ ghcup --version
The GHCup Haskell installer, version v0.1.13
```

ghcup installs HLS 1.0.0:

```
$ ghcup install hls
[ Info  ] downloading: https://github.com/haskell/haskell-language-server/releases/download/1.0.0/haskell-language-server-macOS-1.0.0.tar.gz
```
