### ISSUE TITLE
Cannot Detect GHC although Stack is working properly in the in Environment Variable

### ISSUE THREAD

**Issue by salimp2009** [haskell/vscode-haskell#527]
### Your environment 👍 
Stack Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
VS Code 1.63.2

Which OS do you use:
Windows11

### Steps to reproduce
- Installed extension from VS Code Extensions
- Get a warning "**Project requires GHC but it isn't installed"**
- Have Stack 2.7.3  and works and it is in Environment Variable -> User Variables ->Path :: "C:\Users\User\AppData\Roaming\local\bin\stack.exe"

### Expected behaviour
It should see the GHC and work

### Actual behaviour
- Get a warning "Project requires GHC but it isn't installed"

### Include debug information
NA; 

Debug output:
NA

```

```

Paste the contents of extension specific log, you can check instructions about how to find it [here](https://github.com/haskell/vscode-haskell#troubleshooting)

NA
Extension log:
NA

```

```

**Comment by salimp2009** [comment]
i think it is because the resolver version but not sure i tried different resolver version that are listed supporting ;  i tried another sample code from the latest books it gives this error now (this one uses resolver: lts-11.16) ;

![haskell-error](https://user-images.githubusercontent.com/46407603/154541132-4bac3db8-025f-40c5-9dc5-444fdca37a6a.jpg)

**Comment by salimp2009** [comment]
> Same issue here on Arch Linux, with extension version **1.8.0** on top of VS Code **1.64.2**. Stack and GHC version is as follows.
> 
> ```
> $ stack --version
> Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f (dirty) (8368 commits) x86_64
> $ stack exec -- ghc --version
> The Glorious Glasgow Haskell Compilation System, version 8.10.7
> ```
> 
> Still getting this for single file scenarios. ![image](https://user-images.githubusercontent.com/32769878/154514669-d385c78d-28db-4cb2-8edf-aa2c8db8219b.png)

i think it is related to resolver version; but not sure why every version gives different errors

**Comment by fendor** [comment]
@salimp2009 In the project you want to load, what's your `stack.yaml`? 

Depending on your resolver version, you install a different GHC version, see https://www.stackage.org/ for an overview which resolvers use which GHC version. With that knowledge, you can take a look at https://github.com/haskell/vscode-haskell#supported-ghc-versions and check whether your GHC version is supported by HLS (and transitively, this extension)

**Comment by salimp2009** [comment]
> @salimp2009 In the project you want to load, what's your `stack.yaml`?
> 
> Depending on your resolver version, you install a different GHC version, see https://www.stackage.org/ for an overview which resolvers use which GHC version. With that knowledge, you can take a look at https://github.com/haskell/vscode-haskell#supported-ghc-versions and check whether your GHC version is supported by HLS (and transitively, this extension)

I did as you said and I changed my stack yaml like this ;
```
resolver: lts-18.25
packages: []
```
and also added hie.yaml (after looking at the web site)
```
cradle:
  stack:
    component: "haskell-language-server:lib"
```
Now it does not give me an error . But when I move my mouse over any type , it looks like it is loading but nothing comes up.
Also when i open an existing file, there are always red squiggles and the warning says. 
```
Failed to parse result of calling stack
[0mError parsing targets: Unknown local package: haskell-language-server
Note that to specify options to be passed to GHCi, use the --ghci-options flag[0m
```
and if i just add / delete an empty line then it goes away. There is still somethng I am not doing right. I am not sure

**Comment by fendor** [comment]
Please remove the `stack.yaml`, and/or take a look at the documentation for `hie.yaml` at https://github.com/haskell/hie-bios to understand when this file is necessary.

**Comment by salimp2009** [comment]
> Please remove the `stack.yaml`, and/or take a look at the documentation for `hie.yaml` at https://github.com/haskell/hie-bios to understand when this file is necessary.
> 
> Then, please try again :)

i will try deleting stack. yaml but this confused me more . 
 I was following a class where it showed to add the stack. yaml and so so far every example code i see has a stack. yaml but those probably use packages 
I also recently installed ghcup and i believe it installed a language server too 🙈

**Comment by fendor** [comment]
> i will try deleting stack. yaml but this confused me more .

My apologies, I meant removing `hie.yaml` mental typo! The `stack.yaml` is indeed necessary :)

**Comment by salimp2009** [comment]
> > i will try deleting stack. yaml but this confused me more .
> 
> My apologies, I meant removing `hie.yaml` not to remove `stack.yaml`, I had a mental typo! The `stack.yaml` is indeed necessary :)

thank you I am almost about to give up because I have done that before just having stack. yaml and tried almost every resolver version .
Will do one more time see what happens

**Comment by hasufell** [comment]
> > > i will try deleting stack. yaml but this confused me more .
> > 
> > My apologies, I meant removing `hie.yaml` not to remove `stack.yaml`, I had a mental typo! The `stack.yaml` is indeed necessary :)
> 
> thank you I am almost about to give up because I have done that before just having stack. yaml and tried almost every resolver version .
> Will do one more time see what happens

Is there a reason you're using stack and not cabal?

**Comment by salimp2009** [comment]
> > > > i will try deleting stack. yaml but this confused me more .
> > > 
> > > 
> > > My apologies, I meant removing `hie.yaml` not to remove `stack.yaml`, I had a mental typo! The `stack.yaml` is indeed necessary :)
> > 
> > 
> > thank you I am almost about to give up because I have done that before just having stack. yaml and tried almost every resolver version .
> > Will do one more time see what happens
> 
> Is there a reason you're using stack and not cabal?

it was shown in the class example and following that. But i have cabal in my system. I installed it thru ghcup.
I deleted hie.yaml and now the server crashes and shows this ; 

`The Haskell (firstprogram) server crashed 5 times in the last 3 minutes. The server will not be restarted.`

**Comment by salimp2009** [comment]
> > i will try deleting stack. yaml but this confused me more .
> 
> My apologies, I meant removing `hie.yaml` not to remove `stack.yaml`, I had a mental typo! The `stack.yaml` is indeed necessary :)

I did what you said. I delete hie.yaml and kept the stack.yaml and server crash error shows up ; 
`The Haskell (firstprogram) server crashed 5 times in the last 3 minutes. The server will not be restarted.`

**Comment by fendor** [comment]
@salimp2009 And `stack build` succeeds? Can you please post the logs from the extension? Logs can be found at https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems (Only step 5 and 6 matter probably)

**Comment by salimp2009** [comment]
> @salimp2009 And `stack build` succeeds? Can you please post the logs from the extension? Logs can be found at https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems (Only step 5 and 6 matter probably)

I did trace setting as in the link and here is the output ; Looks like it is looking for hie.yaml this time 

```
2022-03-13 19:53:14.5940000 [client] INFO Searching for server executables haskell-language-server-wrapper,haskell-language-server in $PATH
2022-03-13 19:53:14.5940000 [client] INFO $PATH environment variable: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git LFS;C:\Program Files\PuTTY\;C:\Program Files\Perforce;C:\Program Files\Perforce\;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin;C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python310\;C:\Users\User\AppData\Roaming\local\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Perforce\Server;C:\Users\User\AppData\Local\GitHubDesktop\bin;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\ninja-win;C:\Program Files (x86)\GnuWin32\bin;C:\developer\llvmCustomBuild\llvm-project\build\bin;C:\Program Files\LLVM\bin;C:\Users\User\.dotnet\tools;C:\Users\User\AppData\Roaming\npm;C:\msys64\mingw64\bin;C:\Program Files\qemu;C:\texlive\2021\bin\win32;C:\Users\User\AppData\Roaming\local\bin\stack.exe;C:\Program Files\Vim\vim82\vim.exe;C:\Users\User\AppData\Roaming\ghc;C:\Users\User\AppData\Roaming\local\bin\catn.exe;;C:\ghcup\bin
2022-03-13 19:53:14.6830000 [client] INFO Found server executable in $PATH: haskell-language-server-wrapper
2022-03-13 19:53:14.6830000 [client] INFO Activating the language server in working dir: c:\developer\haskell\haskell_FP\firstprogram (the workspace folder)
2022-03-13 19:53:14.6830000 [client] INFO run command: haskell-language-server-wrapper --lsp -d
2022-03-13 19:53:14.6830000 [client] INFO debug command: haskell-language-server-wrapper --lsp -d
2022-03-13 19:53:14.6830000 [client] INFO server environment variables:
2022-03-13 19:53:14.6840000 [client] INFO Starting language server
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.6.1.0.exe) Version 1.6.1.0, Git revision f4022c5bb8530cd306c53b941878244bf27a5d41 (dirty) x86_64 ghc-8.10.7
Current directory: c:\developer\haskell\haskell_FP\firstprogram
Operating system: mingw32
Arguments: ["--lsp","-d"]
Cradle directory: c:\developer\haskell\haskell_FP\firstprogram
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Failed get project GHC version, since we have a none cradle
[Info  - 22:53:19] Connection to server got closed. Server will restart.
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.6.1.0.exe) Version 1.6.1.0, Git revision f4022c5bb8530cd306c53b941878244bf27a5d41 (dirty) x86_64 ghc-8.10.7
Current directory: c:\developer\haskell\haskell_FP\firstprogram
Operating system: mingw32
Arguments: ["--lsp","-d"]
Cradle directory: c:\developer\haskell\haskell_FP\firstprogram
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Failed get project GHC version, since we have a none cradle
[Info  - 22:53:21] Connection to server got closed. Server will restart.
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.6.1.0.exe) Version 1.6.1.0, Git revision f4022c5bb8530cd306c53b941878244bf27a5d41 (dirty) x86_64 ghc-8.10.7
Current directory: c:\developer\haskell\haskell_FP\firstprogram
Operating system: mingw32
Arguments: ["--lsp","-d"]
Cradle directory: c:\developer\haskell\haskell_FP\firstprogram
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Failed get project GHC version, since we have a none cradle
[Info  - 22:53:23] Connection to server got closed. Server will restart.
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.6.1.0.exe) Version 1.6.1.0, Git revision f4022c5bb8530cd306c53b941878244bf27a5d41 (dirty) x86_64 ghc-8.10.7
Current directory: c:\developer\haskell\haskell_FP\firstprogram
Operating system: mingw32
Arguments: ["--lsp","-d"]
Cradle directory: c:\developer\haskell\haskell_FP\firstprogram
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Failed get project GHC version, since we have a none cradle
[Info  - 22:53:25] Connection to server got closed. Server will restart.
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.6.1.0.exe) Version 1.6.1.0, Git revision f4022c5bb8530cd306c53b941878244bf27a5d41 (dirty) x86_64 ghc-8.10.7
Current directory: c:\developer\haskell\haskell_FP\firstprogram
Operating system: mingw32
Arguments: ["--lsp","-d"]
Cradle directory: c:\developer\haskell\haskell_FP\firstprogram
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Failed get project GHC version, since we have a none cradle
[Error - 22:53:26] Connection to server got closed. Server will not be restarted.
```

**Comment by salimp2009** [comment]
Good new it works when i re-added hie.yaml but this time it is like this and works beautiful. Thank you so much but if you want to some debugging I can do it to see what the problem for the previous version. 
hie.yaml; I am just wondering now what my problem was tough; 
```
cradle:
  stack:
```

**Comment by fendor** [comment]
Not entirely clear why HLS is shutting down here, can you maybe share the project, or the project skeleton you are working on?

The problem seems to be that HLS tried to load a file that is not associated to any "project". 

> Consulting the cradle to get project GHC version...
> Failed get project GHC version, since we have a none cradle

Means we failed to figure out the project ghc version, in this case for a stack project. Very weird.

**Comment by salimp2009** [comment]
it is not a serious project. It was a learning Haskell thing. I can share it no problem
it is this one; 
https://github.com/salimp2009/HaskellProgram/tree/master/firstprogram

I also started a new class and currently no stack.yaml or anything; and it works with no problem. Also tried stack init on the new one where it creates a stack.yaml and that worked fine too

**Comment by hasufell** [comment]
> it is not a serious project. It was a learning Haskell thing. I can share it no problem it is this one; https://github.com/salimp2009/HaskellProgram/tree/master/firstprogram
> 
> I also started a new class and currently no stack.yaml or anything; and it works with no problem. Also tried stack init on the new one where it creates a stack.yaml and that worked fine too

It appears you haven't created a project: I advise to learn cabal https://cabal.readthedocs.io/en/stable/getting-started.html

**Comment by salimp2009** [comment]
> > it is not a serious project. It was a learning Haskell thing. I can share it no problem it is this one; https://github.com/salimp2009/HaskellProgram/tree/master/firstprogram
> > I also started a new class and currently no stack.yaml or anything; and it works with no problem. Also tried stack init on the new one where it creates a stack.yaml and that worked fine too
> 
> It appears you haven't created a project: I advise to learn cabal https://cabal.readthedocs.io/en/stable/getting-started.html

i was following the class. the first section was more about the basic types, data types, basic pattern matching. 
Thanks for the link now i can learn proper way of doing .  I also recently bought Effective Haskell  book which also teaches a proper app dev thru Haskell but they all start with the basics section before going into build system i believe.
thanks a lot tough.
