### ISSUE TITLE
VSCode should be able to manage a Template Haskell supporting HLS

### ISSUE THREAD

**Issue by goldfirere** [haskell/vscode-haskell#528]
**Is your feature request related to a problem? Please describe.**

I'm getting the new "This HLS binary does not support Template Haskell" warning. I understand that I can avoid this if I build from source. But it's nice to have VSCode manage my HLS installation for me, so I'd prefer not to build from source (and need to update it later).

**Describe the solution you'd like**

Have VSCode manage a dynamically linked HLS.

**Describe alternatives you've considered**

I've considered building from source, and (I think) I know how to do this, but then I'm pretty sure I'll have to manually update later.

**Comment by pepeiborra** [comment]
This is being worked on, our first attempt failed and had to be rever  ted last minute during the 1.6 release. The second attempt looks much more promising and will be coming soon (#2678) via ghcup

**Comment by fendor** [comment]
Additionally, we just merged the PR switching to GHCup for HLS management. See #533. 
This will allow VSCode to manage HLS binaries that support template haskell.

**Comment by fendor** [comment]
Closing as ghcup now manages HLS and installs HLS executables that can run TH, iirc.

@hasufell correct me if I am wrong
