### ISSUE TITLE
Is serverExecutablePath actually being deprecated?

### ISSUE THREAD

**Issue by chiroptical** [haskell/vscode-haskell#529]
https://github.com/haskell/vscode-haskell/blob/49321941dd38a4479b29ecf4a657f8392fd04b82/package.json#L140

A colleague of mine recently noticed this "deprecated scope" message. At Mercury we have quite a bit of trouble running HLS on our codebase. A coworker wrote an alternative which provides only type on hover and go to definition and we use this variable to point to the alternate provider. It makes perfect sense to default to hls, but it would be really nice to leave room for an alternate server. Thanks!

**Comment by hasufell** [comment]
The next release will still have it, but you have to make sure to not enable `manageHLS` config option. The extension will ask you if you want that on first start.

**Comment by fendor** [comment]
The deprecation warning is only regarding the scope of the option afaict.

But I don't see why it should be machine scope rather than per-project scope?

**Comment by friedbrice** [comment]
Please reconsider removing the ability to set this option on a per-workspace scope.

Removing the ability to set this option on a per-workspace scope breaks a common and reasonable use case. I'll elaborate.

On most Haskell projects, HLS works just fine and I'd like to be able to use it. However, on one particularly-gnarly project HLS just doesn't work at all. This project happens to be the one I most-frequently work in. On that project's workspace I use `haskell.serverExecutablePath` to use an alternative light-weight, low-feature language server.

Again, this "bad" project happens to be the one I most-frequently work on, and so I definitely need to be using this alternative backend, at least for this one workspace. If `haskell.serverExecutablePath` is changed to global-only scope, then I will be forced to forgo the use of HLS on all my other "good" projects. Needless to say, that would make me very sad.

**Comment by fendor** [comment]
I agree, that seems like a totally legit use-case. 

I have no idea why this deprecation notice was added, I will try to dig in the git logs, but if I can't find any compelling reasoning, this deprecation notice will be deprecated soon. (I.e. it will not be deprecated any longer)

**Comment by friedbrice** [comment]
@fendor This is why we can't have nice things 😞

**Comment by friedbrice** [comment]
As an alternative, a strictly-global scope setting that says `allowWorkspaceExecutable`, that defaults to `false` and that users can change at their own peril. I would totally set it to `true` at my own peril!

**Comment by fendor** [comment]
vscode-clangd uses `machine-overridable`: https://github.com/clangd/vscode-clangd/issues/64 
rust-analyzer also uses `machine-overridable`: https://github.com/rust-lang/rust-analyzer/blob/master/editors/code/package.json#L303
Same for python (which contains many path settings): https://github.com/microsoft/vscode-python/blob/main/package.json#L397 

Documentation for `machine-overridable`: https://code.visualstudio.com/api/references/contribution-points

I can't really tell straight away the difference between `resource` and `machine-overridable`, but seems like we have some reason to switch to `machine-overridable`.

**Comment by mikelpr** [comment]
+1 on please DON'T

I get my HLS and GHC per project via nix expressions. I set haskell.serverExecutablePath to `nix-shell --pure hls.nix --run "haskell-language-server $@"` per workspace, this gets written to `.vscode/settings.json`. This has worked perfectly for me to keep projects on a specific GHC version until I want to update them and have no clashes. Now there's this ominous warning about all this work going to the trash and I don't understand why is it a problem at all and why was it thought the solution would be to get rid of this functionality.

machine-overrideable seems like it fixes your concerns and still allows for setting it for a workspace. I really hope the setting stays

**Comment by fendor** [comment]
serverExecutablePath is no longer deprecated and the scope is set to `machine-overridable`. 

Please shout, if that doesn't work for someone.
