### ISSUE TITLE
What's wrong with my haskell extension? It failed to found GHC version.

### ISSUE THREAD

**Issue by code-brewer** [haskell/vscode-haskell#545]
My ENV:

- MacBook M1 pro
- Had haskell tool installed by ghcup tui, include ghci, cabal, stack

After install haskell plugin and open an project ( cardano plutus-starter peoject), it complained "Couldn't figure out what GHC version the project"

Then i tried:

- install HLS by  ghcup tui, 
- Uninstall haskell extension, delete `~/Library/Application\ Support/Code/User/globalStorage/haskell.haskell/` and install haskell extension again

But the result even worser, their  is no syntax hightligt for .hs file. But see no popup message this time.

After searched on the issues. I pick up one command `haskell-language-server-wrapper  --project-ghc-version` and try it,

```
➜  plutus-starter git:(main) ✗ /Users/brooze//.ghcup/bin/haskell-language-server-wrapper  --project-ghc-version
Found "/Users/brooze/Programming/drills/haskell/plutus_demos/plutus-starter/hie.yaml" for "/Users/brooze/Programming/drills/haskell/plutus_demos/plutus-starter/a"
Failed to get project GHC version:CradleError {cradleErrorDependencies = [], cradleErrorExitCode = ExitFailure 1, cradleErrorStderr = ["Error when calling cabal --builddir=/Users/brooze/.cache/hie-bios/dist-plutus-starter-8692d5890a14508e6c96828df6b9681a v2-exec --with-compiler /Users/brooze/.cache/hie-bios/wrapper-13a09b18ea883dd377d59db5e821a86b ghc -v0 -- --numeric-version","","cabal: Could not resolve dependencies:\n[__0] trying: Win32-network-0.1.0.0 (user goal)\n[__1] trying: base-4.13.0.0/installed-4.13.0.0 (dependency of Win32-network)\n[__2] next goal: base-deriving-via (user goal)\n[__2] rejecting: base-deriving-via-0.1.0.0 (conflict:\nbase==4.13.0.0/installed-4.13.0.0, base-deriving-via => base>=4.14)\n[__2] fail (backjumping, conflict set: base, base-deriving-via)\nAfter searching the rest of the dependency tree exhaustively, these were the\ngoals I've had most trouble fulfilling: base, Win32-network, base-deriving-via\n\n"]}
➜  plutus-starter git:(main) ✗
``` 

Does this error has something related to project that vscode opened?   

Because I just managed to compile this project use `cabal build` on another PC with Ubuntu OS, and saw 'backjumping' error in this process.  The 'backjumping' error was fixed after install `apt-get install libsystemd-dev` package. 
 
No idea what to do now. This is my first time to experience  this haskell extension.

Any suggestion?

**Comment by code-brewer** [comment]
> 

Sorry for leave for these weeks.

On macBook M1,`cabal build` failed because of backjumping lib missing.
Is it necessary  to required `cabal build` successfully to determine the GHC version?  I'm afraid not.

**Comment by fendor** [comment]
> Is it necessary to required cabal build successfully to determine the GHC version?

Your question should be: should it be required that cabal build succeeds to determine the GHC version? Then the answer is no. However, *it is* required that `cabal build` succeeds to successfully determine the GHC version.
I don't want to go into too many details, but it mainly has to do with the fact that cabal is old software and not designed with IDE's and how they work nowadays in mind. If you want details, feel free to ping me on irc/discord or whatever.

**Comment by fendor** [comment]
Closing as we can't fix it here
