### ISSUE TITLE
Syntax Highlighting broken with semicolon

### ISSUE THREAD

**Issue by RSWilli** [haskell/vscode-haskell#548]
### Your environment

Which OS do you use:
ArchLinux

### Steps to reproduce

```haskell
data Picture = Picture

instance Foo Picture ; instance Bar Picture
```

### Expected behaviour
the second instance gets correct syntax highlighting, since it is valid Haskell

### Actual behaviour
the second instance is not recognized as a keyword, and thus not highlighted correctly

It looks like the syntax highlighting for GitHub's code segment also breaks

In VScode this looks similar:

![image](https://user-images.githubusercontent.com/18500203/159133618-ee75aeaa-6b78-48d6-a330-93694327092b.png)

**Comment by fendor** [comment]
Hi, thank you for your bug report! This is not a feature we provide but rather a feature of https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell. Please raise your issue at https://github.com/JustusAdam/language-haskell/issues
