### ISSUE TITLE
Add support for using vscodes rename symbol feature

### ISSUE THREAD

**Issue by Markos-Th09** [haskell/vscode-haskell#560]
**Is your feature request related to a problem? Please describe.**
VSCode has a feature to rename a symbol. That works in all the language I use, expect haskell.

**Describe the solution you'd like**
As mentioned above this is available in every other language I use in vscode expect haskell. I'm really frustrated when I do refactoring of code. This makes refactoring easier because it renames the actual symbols and its references instead replacing every occurrence of the name of it 

**Describe alternatives you've considered**
Replace can get messy when the name of the symbol is used somewhere else as a word, such as a comment.

**Additional context**
[Refactoring in VSCode](https://code.visualstudio.com/docs/editor/refactoring)

**Comment by fendor** [comment]
Hi, thank you for your feature request! You will be glad to here, we are working on it: https://github.com/haskell/haskell-language-server/issues/2193

**Comment by Markos-Th09** [comment]
> Hi, thank you for your feature request! You will be glad to here, we are working on it: [haskell/haskell-language-server#2193](https://github.com/haskell/haskell-language-server/issues/2193)

Awesome
