### ISSUE TITLE
Buggy behaviour when using nix-shell

### ISSUE THREAD

**Issue by KristianBalaj** [haskell/vscode-haskell#577]
I think this started to happen when I switched to 2.0.0 prerelease. However, even when I got back to 1.8.0 stable it remained to happen.

When I open a nix-shell in terminal and run `cabal build` it works as expected (outside of VS Code), however when I run the cabal build inside the VS Code terminal it fails to build because it suddenly cannot resolve dependencies (the VS Code is opened from the nix-shell).

Here I provide the extension's log in a file:
[extension.log](https://github.com/haskell/vscode-haskell/files/8479502/extension.log)

**Comment by KristianBalaj** [comment]
It looks to happen kind of randomly however, I haven't found the exact steps that lead to it. Sometimes it works normally, sometimes it is bugged like mentioned.

**Comment by fendor** [comment]
Hi!

Can you try running this command: 
```
> cabal --builddir=/Users/kristian/.cache/hie-bios/dist-smart-contracts-c7a9e3ba42d31946ec1c6f6007735c36 v2-exec --with-compiler /Users/kristian/.cache/hie-bios/wrapper-13a09b18ea883dd377d59db5e821a86b ghc -v0 -- --print-libdir
```

and check whether this command still fails for you?

**Comment by KristianBalaj** [comment]
Yup just cabal build from inside the `nix-shell`. 

The VS Code from the nix-shell is spinned up the following way (it is a Plutus project):
> cd plutus-apps
> nix-shell
> cd my-project
> code .

The command you've mentioned succeeds for me (however, I've run the command in the working VS Code's terminal, not the bugged one).

I haven't met the buggy behaviour since posting this issue.

**Comment by fendor** [comment]
closing for now, if other issues arise, feel free to re-open!
