### ISSUE TITLE
"haskell-language-server 1.7.0.0 is not available on Darwin" starting vscode with vscode-haskell plugin

### ISSUE THREAD

**Issue by levans** [haskell/vscode-haskell#595]
### Your environment

Which OS do you use:
MacOS (which is "Darwin" of course)
Which LSP client (editor/plugin) do you use:
vscode-haskell
Describe your project (alternative: link to the project):
n/a (but it's stack) 

### Steps to reproduce
Start vscode
It detects a new Haskell-language-server (1.7.0.0)
It fails to find the package for "Darwin"

### Expected behaviour
vscode-haskell should find and load haskell-language-server 1.7.0.0 successfully (without error).
OR it should fall back to using the existing/working version of haskell-language-server, rather than leaving the editor with the language support. 

### Actual behaviour
vscode pops up an error saying:
"haskell-language-server 1.7.0.0 is not available on Darwin. [See the list of supported versions here](https://github.com/haskell/vscode-haskell#supported-ghc-versions)"

**Comment by fendor** [comment]
This should be solved by the latest release of vscode-haskell

**Comment by polux** [comment]
The lastest release of vscode-haskell indeed solved it for me, thanks! Note that I had to upgrade vscode to the latest version in order for the vscode-haskell extension to update itself to its latest version.
