### ISSUE TITLE
Unknown configuration setting "haskell.installGHC"

### ISSUE THREAD

**Issue by mduerig** [haskell/vscode-haskell#596]
### Your environment

Which OS do you use: Linux 5.4.0-109-generic 18.04.1-Ubuntu

### Steps to reproduce

Add the setting "haskell.installGHC": false" to settings.json.

### Expected behaviour

GHC is managed by stack an I'm not being asked to download it. As described in the release announcement https://discourse.haskell.org/t/ann-vscode-haskell-2-0-1-released/4440

### Actual behaviour

I'm being asked whether I want to download GHC. Also VSCode complains with "Unknown Configuration Setting".

**Comment by hasufell** [comment]
The release documentation is outdated. In order to only have the extension manage HLS, see https://github.com/haskell/vscode-haskell#setting-a-specific-toolchain

Specifically

```
{
  "haskell.toolchain": {
    "ghc": null,
    "cabal": null,
    "stack": null
  }
}
```

**Comment by mduerig** [comment]
@hasufell, works like a charm. Thanks for pointing me at the relevant documentation.
