### ISSUE TITLE
Confusing dialog on startup: "Need to download ghc-null"

### ISSUE THREAD

**Issue by mduerig** [haskell/vscode-haskell#597]
### Your environment

Which OS do you use: Linux 5.4.0-109-generic 18.04.1-Ubuntu

### Steps to reproduce

Add the following configuration and start VSCode:

```
    "haskell.toolchain": {
        "hls": "1.6.1.0",
        "ghc": null,
        "cabal": null,
        "stack": null
    }

```

### Expected behaviour

VSCode starts and is ready to use, not displaying "strange" dialogue boxes.

### Actual behaviour

VSCode starts and a dialogue pops up "Need to download ghc-null, continue?" 

![Screenshot from 2022-04-28 10-43-57](https://user-images.githubusercontent.com/729548/165715032-eab44f40-a90c-4a07-89d8-62ce79a42f2c.png)

After confirming with "Yes", everything works normal.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

Do you have GHC installed on your system? If yes, how and which GHC version?

**Comment by mduerig** [comment]
No, I don't have it installed globally. This happens with pure stack projects.

**Comment by mduerig** [comment]
FWIW, I just installed 8.10.7 (via ghcup). This makes the problem go away.

**Comment by fendor** [comment]
Awesome, thank you for the detailed bug report!

**Comment by hasufell** [comment]
Are you using ghc 9.0.2 with stack? Or why do you lock an older HLS version? There's a workaround for the bindist issue: https://github.com/haskell/haskell-language-server/issues/2862#issuecomment-1110987023

**Comment by mduerig** [comment]
> Are you using ghc 9.0.2 with stack?

Yes and it kept crashing HLS so I reverted to 1.6.1.0 for now. But this is not related to this issue as I'm getting the same behaviour also with `"hls": "null",`.
