### ISSUE TITLE
Documentation Link in Hover doesn't always display

### ISSUE THREAD

**Issue by mjrussell** [haskell/vscode-haskell#604]
### Your environment

Which OS do you use:

MacOS M1

### Steps to reproduce

I have 2 projects using the same VScode instance, latest plugin version (2.2.0), same HLS version (1.7.0) and stack (1.7.5) and GHC version (8.10.7).

In both of these projects, I can consistently get the Documentation Hover to show up which is great. What is less consistent is the hyperlink for the Documentation to open on Hackage.

It seems to work properly for things like base as you can see here

![image](https://user-images.githubusercontent.com/1641895/166091450-fac35f65-6429-44e3-a044-b9268a95fcb3.png)

But no so for Conduit, esqueleto, monad-logger, or other dependencies.

![image](https://user-images.githubusercontent.com/1641895/166091493-fb89a4e4-9b11-4d66-8a2f-c51705870b6e.png)

![image](https://user-images.githubusercontent.com/1641895/166091505-8388a8e9-b5db-4034-84e8-a005d9e7cce2.png)

![image](https://user-images.githubusercontent.com/1641895/166091520-81b0d9c0-66c9-46bb-a2a7-4b3c74faeda2.png)

### Expected behaviour

Displays the Documentation link

### Actual behaviour

Sometimes Displays the Documentation Link

### Extra

My setup is a little difficult to run the debugging HLS command, because of some pathing interactions with GHCUP, but you can pretty easily reproduce also with this small repo + branch - https://github.com/mjrussell/haddocset/tree/bump-lts-18. I was trying to get dash docsets, but would rather see now about integrating this better into Vscode Haskell. Im interested in trying to contribute to vscode-haskell myself, but would appreciate some pointers if anyone has ideas on what might be wrong.

Mildly related, but is there also a way to programmatically do this command (Click on Documentation)? Would love a keyboard shortcut to open on hackage for text underneath the cursor. Similar to Go To Definition.

**Comment by mjrussell** [comment]
I did find the commands:
`haskell.openDocumentationOnHackage` and `haskell.showDocumentation` those both return some errors if i try to invoke them with my text on a cursor:
`Cannot destructure property 'hackageUri' of 'undefined' as it is undefined.`

**Comment by liftM** [comment]
I can confirm this. For me, the documentation only shows up on exports from `base` packages.

When I build my dependencies with `documentation: True`, I do get a documentation link on non-`base` packages, but they seem malformed and always point to the `html` package, which is almost always wrong.

**Comment by pepeiborra** [comment]
For docs embedded in hover popups https://haskell-language-server.readthedocs.io/en/latest/configuration.html

For hackage links there are other open issues already.

**Comment by liftM** [comment]
Ah, yup, I see #520 now - I was searching the wrong keywords the first time around.

**Comment by carlwr** [comment]
Posting in case it is of help to others finding this issue.

**Re. getting docs to show in hover popups:**

This will happen if `ghc` is passed the option `-haddock` when it builds the dependencies.

Above in https://github.com/haskell/vscode-haskell/issues/604#issuecomment-1140188127, @pepeiborra posted a link to the docs about how to achieve this with Cabal and Stack:
https://haskell-language-server.readthedocs.io/en/latest/configuration.html#how-to-show-local-documentation-on-hover

For Stack, those docs suggest adding the following to `stack.yaml`:
```yaml
ghc-options:
  '$everything': -haddock
```

This does work, but the same can be achieved with stack-native options which likely would be slightly preferred:

```yaml
build:
  haddock: true
  haddock-internal: true
```
