### ISSUE TITLE
Q: GhCup from docker?

### ISSUE THREAD

**Issue by PavolSvidran** [haskell/vscode-haskell#608]
Hello, I'm just starting out with a haskell on my university project. (Haskell is new for me and VSCode also, mostly i use JetBrains IDEs)
I want to create and run a project inside docker container.  Container is already set up and test code works fine - using cabal.

Your VSCode extension has a lot of features for haskell, but it wants to install GhCup.

I want to ask if it is possible to link GHCup executable for this tool from a docker container.

Thank you for your early reply.

**Comment by hasufell** [comment]
Can you elaborate how your vscode is configured?

Is it this? https://code.visualstudio.com/docs/remote/containers

**Comment by PavolSvidran** [comment]
I saw this extension but no, i just created docker compose + dockerfile(from haskell debian image)  + entrypoint configs for container setup and started it via compose. In VS is used only basic docker extension.

**Comment by PavolSvidran** [comment]
Nevermind, i figuret how it works, ty for reference on remote containers at least, it was solution :)
