### ISSUE TITLE
Updating to the HLS 1.7

### ISSUE THREAD

**Issue by KristianBalaj** [haskell/vscode-haskell#609]
I'm interested what is the process to get the HLS 1.7 to work with VS Code?

Updating the HLS via ghcup is enough or it needs some changes in this repo and a new release?

**Comment by hasufell** [comment]
Just restarting your VSCode should be enough, given that your project GHC version is supported by 1.7.0.0, otherwise GHCup may downgrade to an older version, see here for the compatibility matrix: https://github.com/haskell/ghcup-metadata/blob/master/hls-metadata-0.0.1.json

**Comment by KristianBalaj** [comment]
Thanks.
One last thing, how can I check the running version of the HLS for current session?

**Comment by hasufell** [comment]
You check the debug log of the extension https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems starting from point 5
