### ISSUE TITLE
commands to "Stop" and "Start" HLS, not just "Restart"

### ISSUE THREAD

**Issue by aryairani** [haskell/vscode-haskell#619]
I am often in the situation where my vscode-hosted HLS instance(s) unproductively eat up all my CPU, causing even other applications to time out. 

"Restart Haskell LSP Server" doesn't help; only closing the vscode window does, but then I lose my running terminals and the ability to edit code at all.  I can disable the vscode-haskell plugin, but that also requires an editor restart, and another restart if I want to re-enable it.

**Describe the solution you'd like**

Add a command to "Stop Haskell LSP Server" without restarting it, and another to "Start" it.

**Describe alternatives you've considered**

I described some of my workarounds above. Another alternative would be to really dig in and try to figure out what's going wrong with HLS and/or vscode-hls and submit more technical tickets to the appropriate repos.  However, it seems like this could be useful even if those other issues are resolved!

**Comment by hasufell** [comment]
Doesn't that already exist?

![Screenshot_2022-06-13_10-14-31](https://user-images.githubusercontent.com/1241845/173309938-75e94526-5cfe-488d-91fc-91d057496976.png)

**Comment by fendor** [comment]
Closing since there was not response
