### ISSUE TITLE
Feature: provide a way to complete *only* the name of function, and not the parameter types

### ISSUE THREAD

**Issue by ntc2** [haskell/vscode-haskell#629]
**Is your feature request related to a problem? Please describe.**

When completing function names using IntelliSense, the completion inserts the parameter types in addition to the function name. Most of the time I only want to complete the function name, and so I just have to delete the parameter types which is annoying.

For example, supposing I have some variable `s :: String` and I realize I need to convert it to some other type using `fromString`. Suppose "`^`" is the cursor, then if I position the cursor in front of `s` as in `^ s` and type <kbd>f r s TAB</kbd>, I end up with `fromString String^ s`, but what I want is just `fromString^ s`.

Screenshots:

Before completion:
![before](https://user-images.githubusercontent.com/16421/177026397-072da499-b971-4db5-bd1e-48f4ba1c20d8.png)

What I actually get after completion:
![after-have](https://user-images.githubusercontent.com/16421/177026410-15d05038-943d-4a13-b31c-e298c31bc110.png)

What I want to get after completion:
![after-want](https://user-images.githubusercontent.com/16421/177026405-2858ea5e-1991-4044-b4d3-299164c1b9ae.png)

**Describe the solution you'd like**

I'd like a way to disable the "insert the parameter type" 

Could you provide an option to disable inserting the parameter types when completing names, or an alternative key binding that completes the name but not the parameter types?

**Comment by fendor** [comment]
IIRC, that should be achievable by turning off the option at "Haskell > Plugin > ghcide-completion > Config: Snippets on.

Would you mind trying this option?

**Comment by ntc2** [comment]
Perfect, that worked, thanks!

Here's the JSON setting in case anyone else is looking for this:

``` json
"haskell.plugin.ghcide-completions.config.snippetsOn": false
```
