### ISSUE TITLE
Is it possible to use the HLS plugin for VS Code without ghcup?

### ISSUE THREAD

**Issue by houseofwealth** [haskell/vscode-haskell#630]
### Your environment
Windows 10. I am having trouble installing ghcup. So I wanted to see if it would be possible to get the HLS plugin to work for VS Code without needing ghcup? I have both ghc 8.10.7 and the HLS server on my PATH. Yet when I start up VS Code i get a message saying HLS isn't installed which if i click on it, takes me to the ghcup installation page. Just out of curiousity why does this plugin need ghcup, assuming I am wiling to manage the installation of the various haskell pieces my self?

**Comment by hasufell** [comment]
Yes: https://github.com/haskell/vscode-haskell#downloaded-binaries

**Comment by houseofwealth** [comment]
@fendor that's what I already have (Manage HLS is set to PATH). I agree that the automatic installation would be the better option, but as I mentioned I cannot get ghcup to install so I'm forced down this path.

**Comment by houseofwealth** [comment]
@hasufell Yes I'd already been to that link you sent me - all it  does is instruct me to set haskell.manageHLS to PATH and make sure HLS is in your PATH or set haskell.serverExecutablePath (overrides all other settings) to a valid executable, both of which I have already done. So I am out of ideas, willing to try any other ideas you may have

**Comment by hasufell** [comment]
I don't understand what your issue is. You say you're successfully using the manual method now. So it seeems it works?

**Comment by houseofwealth** [comment]
@hasufell : It now finds the HLS (The name was just the name of the file that I downloaded, which has a version number appended, once I removed that part it was able to find HLS). However that didn't help much because I now get an error message
```
ghcide compiled against GHC 9.2.2 but currently using 8.6.5 
This is unsupported, ghcide must be compiled with the same GHC version as the project. 
```
 Which has me stumped since the HLS page says that the current version of HLS (what I have) is supposedly compatible with 8.6.5. In fact there is no other version of HLS that even works with ghc 8.6.5. Any ideas?

**Comment by hasufell** [comment]
@houseofwealth that's why it's easier to use ghcup (you need to build HLS with the GHC you're gonna use). Can you elaborate what doesn't work with ghcup?

**Comment by houseofwealth** [comment]
Powershell just closes without any error messages after (trying to?) execute the last command in this command sequence copied from the ghcup page:  (Its supposed to execute that last command and then give you some install choices)
`Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $true`

**Comment by hasufell** [comment]
Did you disable antivirus and windows defender?

**Comment by houseofwealth** [comment]
So it turns out it wasn't antivirus or windows defender but my company that was blocking the remote script execution b/c its whitelist based. I might have guessed. I tried it on a different machine and it worked. Sorry for the hassle.
