### ISSUE TITLE
VSCode 1.69.2: HLS unable to find the project's ghc version

### ISSUE THREAD

**Issue by why-not-try-calmer** [haskell/vscode-haskell#666]
### Your environment

Which OS do you use?
- Pop!_OS

Which version of GHC do you use and how did you install it?
- 9.0.2 installed from ghcup, managing project with Stack, using `system-ghc: True` from Stack's global configuration file

How is your project built (alternative: link to the project)?
- with Stack

Which LSP client (editor/plugin) do you use?
- VSCode 1.69.2 using the HLS extension

Which version of HLS do you use and how did you install it?
- hls 1.7.0.0, latest, recommended, installed from ghcup

Have you configured HLS in any way (especially: a `hie.yaml` file)?
- No.

### Steps to reproduce
Open my project's folder/workspace.

### Expected behaviour
HLS used to pick up the right GHC version instantly. It was working for months until a few days ago.

### Actual behaviour
For a couple of days it's been running into an issue that has materialized with the following errors and warnings:

```
ghc --numeric-version exited with exit code ENOENT. Consult the [Extensions Output](https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems) for details.
```
and

```
I had trouble figuring out the exact GHC version for the project. Falling back to using 'ghc'.
```
### Debug information

See below.

### Comments
Matrix user @drsooch:matrix.org has kindly provided a workaround: launching VSCode from a terminal makes everything work as expected again. It's not a sustainable solution but mentioning it _en passant_. Also I've doubled-checked that my $PATH envar read the same when shown from a normal terminal and in VSCode's terminal (it does).

**Comment by why-not-try-calmer** [comment]
After flipping through the Output I got this:

```
2022-08-05 07:41:32.7500000 [client] ERROR Error executing 'ghc --numeric-version' with error code ENOENT
2022-08-05 07:41:32.7500000 [client] ERROR stderr: 
2022-08-05 07:41:32.7500000 [client] ERROR Error executing 'ghc --numeric-version': name = Error, message = spawn ghc ENOENT
2022-08-05 07:41:32.7500000 [client] ERROR Internal Error: `ghc --numeric-version` exited with exit code ENOENT.
                              Consult the [Extensions Output](https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems)
                              for details.
2022-08-05 07:41:32.7520000 [client] ERROR Error: `ghc --numeric-version` exited with exit code ENOENT.
                              Consult the [Extensions Output](https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems)
                              for details.
	at /home/hades/.vscode/extensions/haskell.haskell-2.2.0/dist/extension.js:1:433058
	at exithandler (node:child_process:413:5)
	at ChildProcess.errorhandler (node:child_process:425:5)
	at ChildProcess.emit (node:events:402:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
	at onErrorNT (node:internal/child_process:477:16)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by why-not-try-calmer** [comment]
Ok it seems I have managed to narrow it down a bit: all and only my projects built statically with:
```
# package.yaml
ghc-options:
- -static
cc-options:
- -static
ld-options:
- -static

exhibit this issue. So it seems that HLS somehow confuse by my choice of build settings.

**Comment by fendor** [comment]
the culprit is definitely that VSCode did not find ghc or anything else for that matter on the PATH.
That's why launching from the Terminal fixes it, because the PATH is set up correctly.

I don't know why it changed from working to not working, though.

**Comment by why-not-try-calmer** [comment]
> the culprit is definitely that VSCode did not find ghc or anything else for that matter on the PATH. That's why launching from the Terminal fixes it, because the PATH is set up correctly.
> 
> I don't know why it changed from working to not working, though.

Thanks for your reply. Anything I can do to offer you more actionable information?

**Comment by hasufell** [comment]
> > the culprit is definitely that VSCode did not find ghc or anything else for that matter on the PATH. That's why launching from the Terminal fixes it, because the PATH is set up correctly.
> > 
> > I don't know why it changed from working to not working, though.
> 
> Thanks for your reply. Anything I can do to offer you more actionable information?

https://github.com/haskell/vscode-haskell#stackcabalghc-can-not-be-found

**Comment by why-not-try-calmer** [comment]
> > > the culprit is definitely that VSCode did not find ghc or anything else for that matter on the PATH. That's why launching from the Terminal fixes it, because the PATH is set up correctly.
> > > I don't know why it changed from working to not working, though.
> > 
> > 
> > Thanks for your reply. Anything I can do to offer you more actionable information?
> 
> https://github.com/haskell/vscode-haskell#stackcabalghc-can-not-be-found

Thank you very much.

**Comment by artisdom** [comment]
If you're using Arch Linux, 
you can add this new file ghcup_path.sh to /etc/profile.d/ to add the "ghcup" PATH for all users
```
$ cat /etc/profile.d/ghcup_path.sh

[ -d /home/user/.ghcup/bin ] && append_path '/home/user/.ghcup/bin'
export PATH
```

btw, replace "/home/user/.ghcup/bin" with the correct path in your system first.
