### ISSUE TITLE
`Go to definition` and `Find usages` seem to be missing

### ISSUE THREAD

**Issue by RichardJECooke** [haskell/vscode-haskell#697]
### Your environment

Which OS do you use: Kubuntu 22.10

### Steps to reproduce
I expect when I right click on a function the context menu should give me the options `Go to definition` and `Find all usages`.
The former will jump me to where a function is defined, and the latter will show a list of all files and locations where a function is called. This the most basic typed language support I'm used to in an IDE, and I can see the `go to definition` part is in your feature list.

But I don't know how to use it. If I right click a function, as you can see below, the command isn't available. Please help.

![image](https://user-images.githubusercontent.com/5468805/187472676-edd37d85-803d-4b0a-ac52-8647f5993335.png)

**Comment by fendor** [comment]
Hi, thank you for your bug report!

Please follow the instructions from here to see the logs: https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems

**Comment by RichardJECooke** [comment]
Closing. When I restarted my computer today HLS asked to install a new GCH and then these functions became available.
