### ISSUE TITLE
How to prevent `Apply hint` changing tabs to spaces?

### ISSUE THREAD

**Issue by RichardJECooke** [haskell/vscode-haskell#701]
How do I prevent the hint applier (like remove redundant brackets) from changing all my indentation and changing my tabs to spaces please? I can't see a setting in the config.

And also, how do I turn off the indentation underliner completely in my code please?

**Comment by fendor** [comment]
Hi, thank you for the bug report! This feature is provided by the Haskell Language Server, and the discussion and bug-fix should happen in haskell/haskell-language-server#3141

**Comment by fendor** [comment]
Closing, since this is an issue in apply-refact as https://github.com/haskell/haskell-language-server/issues/3141 says
