### ISSUE TITLE
vscode-haskell insist on installing HLS 1.8.0 while version 1.7.0 have been installed.

### ISSUE THREAD

**Issue by StephenChips** [haskell/vscode-haskell#708]
### Your environment

Which OS do you use:

Windows

### Steps to reproduce

Today I opened VSCode and was going to write some Haskell code. VSCode told me that it needed to download hls-1.8.0.0. I clicked "No“ and it complained that "Project requries HLS but it isn't installed", and the intellisense just didn't work anymore. This whole thing is absurd, since I have installed hls-1.7.0.0, and according to `ghc list`, it is the recommended version.

**Step One**
<img width="701" alt="cap" src="https://user-images.githubusercontent.com/17926083/190313522-b786a9fc-75ef-4d2a-8adc-963ea3d48641.PNG">

**Step Two: After clicking "No"**

![image](https://user-images.githubusercontent.com/17926083/190313610-af27a432-6539-4a17-b469-08b848396cfb.png)

### Expected behaviour

I am satisfied with the old version and don't want to upgrade my HLS, so I expect the VSCode will stick on using hls-1.7.0.0 if I denied the upgrade.

### Actual behaviour

The HLS failed to turn on.

### What I want

I want to know how to disable this auto upgrade thing.

**Comment by StephenChips** [comment]
Plus, even I said "Yes" it still failed to download. The reason is clear: the new version of HLS isn't listed in the ghc-metadata file, it is outdated. To me this is quite annoying since everytime I am going to install new version of toolchain this error shows up and I have to figure out why. Then I have to manually find the newest version of ghcup-metadata's URL and copy it into the config file.

**Comment by pepeiborra** [comment]
@fendor is this working as expected?

**Comment by StephenChips** [comment]
The 1.7.0.0 is recommanded because I have not update the metadata file yet. After I updated, 1.8.0.0 become the recommended one.

**Comment by fendor** [comment]
Yes, it is working as expected, I mentioned it to @hasufell before, but adding that logic makes the extension code more complicated. If people do not want to fare with the latest and greatest HLS version, they are encouraged to manage the HLS version by themselves by changing `manageHLS: PATH`, and then instructing ghcup to install the HLS version you want.

I am not opposed to make this behaviour more reasonable, but it will most likely require a flow chart by now to make sure we cover all program flows.

**Comment by hasufell** [comment]
The point is... we should not have bumped 'recommended' tag so quickly.

**Comment by StephenChips** [comment]
@fendor 

IMO, we'd better give a chance for users to say no and choose to use an older version. Now I have known we can do it by the method you mentioned above, but it isn't quite user-friendly. More importantly, I had trouble on installing the newest version of HLS (no matter through VSCode or the command line), which is related to this issue: 

https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/414

Since I couldn't install the latest version and I didn't know how to stop the plugin from updating automatically, I have to wrote codes without intellisense, which was a very very awful experience.

I think we can improve the popup a little bit. When a user click "No", the pop-up window will dismiss and he/she will stick to the older version of HLS. The pop-up window will show at the next time, when he/she reopen a Haskell project with VSCode. We can further add two checkboxes to the pop-up window, which indicate:

1. ☑ **Checkbox No.1**: Do not show me this window again (until the next new version of HLS is released). I will update it 
through command line later.
2. ☑ **Checkbox No.2**: Just update HLS at the background and never show this pop-up window to me EVER again.

There is another reason why I prefer upgrading HLS through ghcup command line over VSCode: GHCup calls cURL for downloading new packages, and while downloading cURL will print out a detailed table on the terminal that shows the current download progress. This is not available if I choosew to update HLS in VSCode. All I can see is just a simple loading bar that seems never ends, which make me a little bit anxious.

![image](https://user-images.githubusercontent.com/17926083/190431122-b77e637b-7f50-42b0-b0b9-0d92350924dc.png)

**Comment by hasufell** [comment]
@StephenChips downgrading to an older toolchain is clearly documented: https://github.com/haskell/vscode-haskell#setting-a-specific-toolchain

```json
{
  "haskell.toolchain": {
    "hls": "1.7.0.0"
  }
}
```

**Comment by StephenChips** [comment]
@StephenChips Thank you. I should apologize that I didn't read the document throughoutly.

**Comment by hasufell** [comment]
This should all be fixed now. Windows and Ubuntu should work.
