### ISSUE TITLE
Load GHCI button does not work with file names with spaces

### ISSUE THREAD

**Issue by jgrocha** [haskell/vscode-haskell#760]
Load GHCI action should protect the filename using quotes.

### Your environment

Ubuntu

### Steps to reproduce

Create a file name with spaces, like "once upon a time.lhs"

### Expected behaviour

Load GHCI button should run: 

```
stack ghci --ghci-options "once upon a time.lhs"
```
### Actual behaviour

```
stack ghci --ghci-options once upon a time.lhs
```

**Comment by fendor** [comment]
We don't have such a button, that's probably a different plugin
