### ISSUE TITLE
Don't create `~/.cabal` if `~/.config/cabal` exists

### ISSUE THREAD

**Issue by geekosaur** [haskell/vscode-haskell#788]
### Your environment

Which OS do you use? Ubuntu 20.04
Which version of GHC do you use and how did you install it? 9.2.5 from ghcup
How is your project built (alternative: link to the project)? `https://github.com/geekosaur/xmonad.hs/tree/skkukuk`
Which LSP client (editor/plugin) do you use? VS Codium+vscode-haskell
Which version of HLS do you use and how did you install it? 1.8.0.0 from ghcup
Have you configured HLS in any way (especially: a `hie.yaml` file)? No

### Steps to reproduce

Start HLS. (This will fail in my configuration because ghc 9.2.5 is not supported, but that's a separate ticket.) 

### Expected behaviour

`~/.cabal` is not created if `~/.config/cabal` exists.

### Actual behaviour

Cabal 3.9/3.10pre supports XDG compliance, which moves various cabal files to XDG compliant locations and no longer uses `~/.cabal`. If it finds `~/.cabal` it switches to compatibility mode. Starting HLS currently always creates `~/.cabal` and I must remove it after starting HLS by any means so my package store will be found.

Cabal 3.10 is currently in pre-release testing, so this currently affects only a few people but will likely become more common as the 3.10 release date approaches.

**Comment by geekosaur** [comment]
`haskell-language-server-wrapper` appears to have run the `cabal` corresponding to its `ghcup` install. I would have expected it to use one on `$PATH`.

I did not explicitly manage it with `ghcup`; it's finding it because I'm using XDG paths (`~/.local/bin`).

**Comment by fendor** [comment]
Yeah, it does, but vscode-haskell manipulates the PATH to make sure sane versions are installed and used.
Just tell vscode-hasell to not handle these tools by specifying the toolchain as above.

**Comment by geekosaur** [comment]
Looks like it still used the wrong `cabal`.

**Comment by geekosaur** [comment]
I've confirmed that it still uses the wrong `cabal`, even if I specify the correct one in settings.

**Comment by geekosaur** [comment]
Okay, I've tracked down the call to inside `hie-bios` (`runGhcCmd`, with `cabal` wrapper via the cradle settings) and in fact it uses `$PATH` there, so apparently it's `vscode-haskell` indeed that sets the wrong path. Which leaves why I originally replicated it from a shell, but as it doesn't happen any more I guess I'll never know.

**Comment by fendor** [comment]
Forcing the extension to not install a cabal via https://github.com/haskell/vscode-haskell/issues/788#issuecomment-1364113490 should work fine, so closing
