### ISSUE TITLE
Allow a list of paths to try for the HLS binary, include `haskell-language-server` by default.

### ISSUE THREAD

**Issue by michaelpj** [haskell/vscode-haskell#845]
There are two main ways you can end up with HLS installed:
1. You install it from a bindist or similar. This typically means you end up with several HLS binaries plus the wrapper.
2. Your install it from Hackage or similar. This is more common for Nix users since they tend to have a project-specific setup that  includes a specific GHC and HLS.

The problem at the moment is that you have to _pick_ whether the extension will try to launch `haskell-language-server-wrapper` or `haskell-language-server`. The most important effect of this is that we can't provide a default config that works for both methods 1 and 2.

Here's a proposal to fix this: make `serverExectuablePath` into _list_ of strings, try those executables in priority order. Then we can make the default value `["haskell-language-server-wrapper", "haskell-language-server"]`, which I think would make everyone happy.

**Comment by hasufell** [comment]
I'm not sure I understand.

The default is empty:

https://github.com/haskell/vscode-haskell/blob/14381068db7dc89124b750017b686995d258bc1c/package.json#L140-L145

And for good reason. I don't see why a user would want to explicitly set `["haskell-language-server-wrapper", "haskell-language-server"]`. There seems to be some other use case that isn't explained here?

**Comment by michaelpj** [comment]
Perhaps I have misunderstood. Do we already look for both `haskell-language-server-wrapper` and `haskell-language-server`? I've had people complain that e.g. if they have a shell with just `haskell-language-server` it doesn't work out of the box and they have to set `serverExecutablePath`.

**Comment by michaelpj** [comment]
Alright, looks like I'm out of date!
