### ISSUE TITLE
Marketplace Access Token has expired

### ISSUE THREAD

**Issue by fendor** [haskell/vscode-haskell#941]
We can't release without that token :( https://github.com/haskell/vscode-haskell/actions/runs/5893610865

ping @jaspervdj  who gave us the token last time.

**Comment by jaspervdj** [comment]
I don't have access to that anymore since my committee term ended, I just asked them if anyone would like to take this over.  I'll keep you updated.

**Comment by jaspervdj** [comment]
I am working on this with @aaronallen8455.  In the meantime, do you have a public GPG key we can use to encrypt the new token before sending it to you?

**Comment by fendor** [comment]
Does this work? https://keys.openpgp.org/search?q=9849506453CA97E75F505D054EF829564CA34FC8

**Comment by jaspervdj** [comment]
That should work yes; the new token should now be in the inbox of the email address associated with the GPG key (`h***@posteo.net`).  It expires in a year.  It would be good to put some sort of reminder at now+11 months to take care of this again?

**Comment by fendor** [comment]
Perfect, thank you very much!

**Comment by fendor** [comment]
I think I need a token for VSCodium Marketplace as well?

**Comment by jaspervdj** [comment]
@fendor I made you an owner of the extension on Open VSX.  You need to login there using Github, then you should be able to see "haskell" extension listed here:

https://open-vsx.org/user-settings/extensions

And you should be able to generate a new token here:

https://open-vsx.org/user-settings/tokens

To write to the committee, just use `committee@haskell.org`, we usually respond pretty fast.

**Comment by jaspervdj** [comment]
> EDIT: Subject line says Azure Token, is this an access token for the VSCode marketplace?

Yes, the VSCode marketplace is part of the Azure dev portal

**Comment by jaspervdj** [comment]
FWIW, the Open VSX token seems like it's still valid, and the error in the pipeline is only about the VSCode Marketplace, so the Open VSX one may not need refreshing (but probably can't hurt either).

**Comment by fendor** [comment]
Release was successul, thank you very much for your prompt response!
