### ISSUE TITLE
Add ghcup to PATH automatically

### ISSUE THREAD

**Issue by hasufell** [haskell/vscode-haskell#962]
https://discourse.haskell.org/t/haskell-and-vs-code-issues/7663

Comes up very frequently. The extension can probe for ghcup and if it's not in PATH, suggest to add it via `haskell.serverEnvironment`.

@fendor

**Comment by fendor** [comment]
How do we probe for ghcup?

We can guess all the locations ghcup installs itself into when installed via curl.
Further, we can guess locations by looking at XDG_DIR directories.
Should we also look at package managers to see to which location these install ghcup to, or is that a bad idea?

**Comment by hasufell** [comment]
We try to invoke it directly. If that works, then we run `ghcup whereis bindir` to get the actual binary dir (ghcup isn't guaranteed to reside there, e.g. when installed via package managers) and add that to PATH.

If that doesn't work, we follow this logic to guess the ghcup basedir: https://github.com/haskell/ghcup-hs/blob/371eda962f713fe483616310291004a82e5b029d/lib/GHCup/Utils/Dirs.hs#L202

Then check if a ghcup binary is in the `bin/` subdir. If so, we add that to PATH.

**Comment by fendor** [comment]
> We try to invoke it directly.

Doesn't that only work if it already is on the PATH?

Rest looks sensible.

**Comment by hasufell** [comment]
> Doesn't that only work if it already is on the PATH?

Yes, but it might be in `/usr/bin`, but the ghcup bindir is `~/.ghcup/bin`.

**Comment by fendor** [comment]
Right, but if ghcup is on the PATH, then the extension will find it and ghcup works as expected.
The bindir of ghcup doesn't need to be on the PATH, since ghcup sets up all the tools in a tmpdir and adds *that* to the PATH.

Or is the point to unconditionally add ghcup bindir to the PATH via serverEnvironment?

**Comment by hasufell** [comment]
> Or is the point to unconditionally add ghcup bindir to the PATH via serverEnvironment?

We probably should, since `ghcup upgrade` doesn't do an in-place upgrade, but puts it into GHCup bindir.

https://github.com/haskell/vscode-haskell/blob/aef73c2d13c49dcb4aa9a8ef61f9ac058c1cf344/src/hlsBinaries.ts#L552

However, we need to make sure this doesn't take precedence over other user configurations, so I'm wondering if we should **append** to PATH, just in case of weird shenanigans (like someone putting ghcup binary into a custom dir and adding that via haskell.serverEnvironment to the PATH... then we don't want to overrule it).

**Comment by hasufell** [comment]
> (like someone putting ghcup binary into a custom dir and adding that via haskell.serverEnvironment to the PATH... then we don't want to overrule it).

Although that case is fine, since we'll find the binary there anyway and won't guess the ghcup bindir.

Still think it's safer to append.

**Comment by hasufell** [comment]
Hm, but if we append, `ghcup upgrade` won't take effect.

**Comment by hasufell** [comment]
Yeah, I guess most conservative method is to do nothing if we find a ` ghcup` binary in PATH. Otherwise we probe and prepend to PATH.

**Comment by hasufell** [comment]
Actually we don't need to touch PATH at all, since we're only interested in the binary: https://github.com/haskell/vscode-haskell/pull/963

**Comment by hasufell** [comment]
Do we want to make a release?

**Comment by fendor** [comment]
Ideally, we have some more manual tests. But yes, there is no big change expected in the near future, might as well release this week.

**Comment by July541** [comment]
I haven't followed this thread, but our master branch has a bunch of unrelated error messages introduced by hls-cabal-plugin, not sure if it has been fixed.

See release note https://github.com/haskell/vscode-haskell/releases/tag/2.5.0
